"""Generates Honeycomb Catacombs' PLACEHOLDER art from the handful of real source images.

Not part of the game. Nothing in scripts/ runs this or knows it exists; it is a one-shot tool for
producing stand-in assets so the game reads correctly before it is drawn properly.

THE LAYOUT IT PRODUCES  (matches honeycomb-art.js -- change both together)

    characters/<character>/<outfit>/0-portrait      the face, for rosters and rails
    characters/<character>/<outfit>/1-basic         standing, healthy
    characters/<character>/<outfit>/1-damaged       recoiling, healthy
    characters/<character>/<outfit>/1-offense       attacking, healthy
    characters/<character>/<outfit>/1-passive       non-attack action, healthy
    characters/<character>/<outfit>/2-*             the same four, hurt
    enemies/<enemy>/<variant>/...                   identical shape

Eight sprites plus a portrait per outfit, and nothing more. The numeric prefix is a health tier
(1 healthy, 2 hurt); the word after it is a pose. Files therefore sort into a readable order inside
each folder -- portrait, then every healthy pose, then every hurt pose -- so an art pass can see at a
glance what exists and what is missing.

WHAT IS DELIBERATELY NOT GENERATED

  * State art. Statuses are drawn as CSS filters over the base sprite (honeycomb.art.stateArray),
    which costs zero images. Only a status that genuinely deserves a drawn pose gets a folder, and
    that is an art decision rather than something to bulk-generate.
  * Symbolic icons -- statuses, resources, node types, intents. Those are inline SVG generated at
    runtime by honeycomb.ui.glyph, which is the right home for a shape that will become a drawn icon.

Dropping a real .webp into any of these paths makes the game prefer it immediately, with no code
change: the resolver walks a fallback chain and stops at the first file that loads.

Rerunning is safe and deterministic: every output is overwritten from the sources, no output is ever
a source, and the noise functions are seeded hash walks rather than `random`.

Usage:
    python "!designDocs/honeycomb/tools/generate-placeholder-art.py"
    python "!designDocs/honeycomb/tools/generate-placeholder-art.py" --force

Without --force the script never touches a file it did not write itself, so real art dropped in during
an art pass is safe. Use --force to reclaim every path as a placeholder again -- which is also what a
first run on a tree that predates the manifests needs, since files with no manifest are indistinguish-
able from real art and are protected by default.
"""
import io
import os
import shutil
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageEnhance, ImageChops, ImageFont, ImageOps

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
ART = os.path.join(ROOT, "v13 spire images")
# The full-size originals of every drawing, kept forever by png-to-webp.py. An outfit copy is recoloured
# from here when the original exists, so it is not a recompression of an already-compressed webp.
PNG_ARCHIVE = os.path.join(ROOT, "v13 spire png")

WEBP_QUALITY = 88

# The only real art in the folder. Everything else is derived from these and may be deleted freely.
# Absolute, so os.path.join(ART, SOURCE_DIR, ...) and art_path(...) resolve here, not under ART.
SOURCE_DIR = os.path.join(ROOT, "!designDocs", "honeycomb", "!imageStorage", "_source")
SOURCE_CHARACTERS = ["knight", "necro", "vamp", "lancer", "priest", "seer"]
# Enemy sources are one drawing per enemy since session 11 (the single tinted placeholder they replaced
# could not be shipped). See ENEMY_SOURCES for which drawing is which enemy.

GENERATED_ROOTS = ["characters", "enemies"]

# Name of the manifest written into every folder this script produces.
#
# THIS SCRIPT MUST NEVER DELETE REAL ART. An art pass replaces generated placeholders in place, so a
# generator that wiped its output folders would eat that work on the next run. Instead each folder
# gets a manifest listing exactly what this script wrote, and a rerun deletes ONLY files named in the
# previous manifest. A file that is not listed -- real art, a note, anything -- is left alone, while a
# placeholder orphaned by a renamed outfit is still cleaned up.
MANIFEST_NAME = ".generated.txt"

# Set by --force. Makes the script treat every output path as its own, overwriting real art.
FORCE = False
MANIFEST_HEADER = (
    "# Files in this folder generated by generate-placeholder-art.py\n"
    "# Anything NOT listed here is left untouched when the generator reruns.\n"
    "# Replacing a placeholder with real art? Delete its line below and it is never overwritten.\n"
)

# SESSION 35: `combat` is the side-facing standing pose the battle screen rests on. `basic` stays
# front-facing for teambuilding, portraits and menus. Front-facing figures read badly in a fight --
# a row of characters staring at the player rather than at the enemies they are hitting.
POSES = ["basic", "combat", "damaged", "offense", "passive"]
TIERS = [1, 2]


def art_path(*parts):
    path = os.path.join(ART, *parts)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return path


# Loaded sources, cut out once per run: the cut-out is the slow part and card art reads each source again.
SOURCE_CACHE = {}


def load_source(kind, stem):
    """Sources are read from _source/ if present, else from the original flat folders.

    A source with no transparency (the session 8 characters arrived as RGB on white) is cut out in memory
    by cut_out_white_background. The source file itself is never rewritten.
    """
    key = (kind, stem)
    if key in SOURCE_CACHE:
        return SOURCE_CACHE[key].copy()
    for candidate in (
        os.path.join(ART, SOURCE_DIR, kind, stem + ".webp"),
        # Session 19's art pass added .png sources (priest, seer); they are read like any other and
        # cut out in memory when they arrive opaque on white.
        os.path.join(ART, SOURCE_DIR, kind, stem + ".png"),
        os.path.join(ART, kind, stem + ".webp"),
        os.path.join(ART, kind, stem + ".png"),
        os.path.join(ART, "full" if kind == "characters" else "enemy", stem + ".webp"),
    ):
        if os.path.exists(candidate):
            opened = Image.open(candidate)
            has_alpha = opened.mode in ("RGBA", "LA") or "transparency" in opened.info
            image = opened.convert("RGBA") if has_alpha else cut_out_white_background(opened.convert("RGB"), CUTOUT_EXTRA_SEEDS.get(stem, []))
            SOURCE_CACHE[key] = image
            return image.copy()
    raise SystemExit("Missing source image for %s/%s" % (kind, stem))


# How close to pure white a pixel must be to count as background, per channel.
CUTOUT_WHITE_FLOOR = 232
# Pixels of the edge eaten back into the figure, which removes the pale fringe anti-aliasing leaves.
CUTOUT_ERODE_PIXELS = 2
# Softening of the final edge, in pixels.
CUTOUT_FEATHER_RADIUS = 1.2
# Page showing through a gap the line art closes off (Cinder's staff meets her hat and cape, fencing in a
# strip of white). Seeds as (x, y) fractions of the image; the white region under each is background too.
CUTOUT_EXTRA_SEEDS = {
    "lancer": [(0.21, 0.5), (0.2, 0.25), (0.27, 0.22), (0.23, 0.33)],
}


def cut_out_white_background(image, extra_seeds=()):
    """Makes the white page around a figure transparent.

    Only near-white pixels CONNECTED TO THE BORDER are removed, so white clothing inside the line art (a
    robe, stockings, a collar) survives: the outline closes it off from the page.
    """
    import numpy
    from scipy import ndimage
    pixels = numpy.asarray(image)
    near_white = numpy.all(pixels >= CUTOUT_WHITE_FLOOR, axis=2)
    labels, _ = ndimage.label(near_white)
    border = numpy.concatenate([labels[0, :], labels[-1, :], labels[:, 0], labels[:, -1]])
    seeded = [labels[int(y * (labels.shape[0] - 1)), int(x * (labels.shape[1] - 1))] for x, y in extra_seeds]
    border = numpy.concatenate([border, numpy.array(seeded, dtype=border.dtype)])
    background_labels = numpy.unique(border[border > 0])
    background = numpy.isin(labels, background_labels)
    figure = ~background
    if CUTOUT_ERODE_PIXELS > 0:
        figure = ndimage.binary_erosion(figure, iterations=CUTOUT_ERODE_PIXELS)
    alpha = Image.fromarray((figure * 255).astype("uint8"), "L").filter(ImageFilter.GaussianBlur(CUTOUT_FEATHER_RADIUS))
    result = image.convert("RGBA")
    result.putalpha(alpha)
    return result


def save(image, *parts):
    image.save(art_path(*parts), "WEBP", quality=WEBP_QUALITY, method=4)


# ---------------------------------------------------------------------------------------------------
# Image helpers
# ---------------------------------------------------------------------------------------------------
def tint(image, color, strength):
    flat = Image.new("RGBA", image.size, color + (255,))
    blended = Image.blend(image.convert("RGBA"), flat, strength)
    blended.putalpha(image.getchannel("A"))
    return blended


def shift_hue(image, degrees):
    alpha = image.getchannel("A")
    h, s, v = image.convert("RGB").convert("HSV").split()
    h = h.point(lambda value: int((value + degrees * 255 / 360) % 256))
    result = Image.merge("HSV", (h, s, v)).convert("RGBA")
    result.putalpha(alpha)
    return result


def adjust(image, brightness=1.0, saturation=1.0, contrast=1.0):
    alpha = image.getchannel("A")
    rgb = image.convert("RGB")
    if brightness != 1.0:
        rgb = ImageEnhance.Brightness(rgb).enhance(brightness)
    if saturation != 1.0:
        rgb = ImageEnhance.Color(rgb).enhance(saturation)
    if contrast != 1.0:
        rgb = ImageEnhance.Contrast(rgb).enhance(contrast)
    result = rgb.convert("RGBA")
    result.putalpha(alpha)
    return result


def blotches(image, count, radius_fraction, color, seed):
    """Soft coloured blobs clipped to the silhouette. Stands in for wounds on a hurt-tier sprite."""
    width, height = image.size
    alpha = image.getchannel("A")
    layer = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)

    state = seed
    radius = max(2, int(min(width, height) * radius_fraction))
    for _ in range(count):
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        x = int((state >> 8) % width)
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        y = int((state >> 8) % height)
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        size = radius // 2 + int((state >> 8) % radius)
        draw.ellipse([x - size, y - size, x + size, y + size], fill=color + (200,))

    layer = layer.filter(ImageFilter.GaussianBlur(radius * 0.35))
    layer.putalpha(ImageChops.multiply(layer.getchannel("A"), alpha))
    return Image.alpha_composite(image, layer)


def lean(image, degrees, lift_fraction):
    """Rotates and lifts a sprite. Stands in for an action pose without redrawing the figure."""
    width, height = image.size
    rotated = image.rotate(degrees, resample=Image.BICUBIC, expand=False,
                           center=(width // 2, int(height * 0.92)))
    if lift_fraction:
        shifted = Image.new("RGBA", image.size, (0, 0, 0, 0))
        shifted.paste(rotated, (0, -int(height * lift_fraction)), rotated)
        return shifted
    return rotated


def head_crop(image, size):
    """A square crop around the head, for the portrait. Sources are full-body 1:2, head at the top."""
    width, height = image.size
    box = int(width * 0.62)
    left = (width - box) // 2
    top = int(height * 0.035)
    cropped = image.crop((left, top, left + box, top + box))
    return cropped.resize((size, size), Image.LANCZOS)


PORTRAIT_SIZE = 256

# Sprites are capped at this height, and it is also the RECOMMENDED DELIVERY SIZE for real art.
#
# The reasoning: a fighter occupies at most ~60% of the stage height. On a 1080p screen that is ~650
# display pixels, so ~1300 covers a 2x/retina panel with room to spare. The 1408x2816 source art is
# more than twice that in each direction and four times the pixels -- which cost 16MB across the
# generated set and visibly delayed the first paint of a battle for no visual gain whatsoever.
#
# Raise this if the game ever renders fighters larger; there is no reason to ship more.
SPRITE_MAX_HEIGHT = 1300


def cap_height(image, maximum=None):
    """Downscales to the sprite height cap, preserving aspect. Never upscales."""
    limit = SPRITE_MAX_HEIGHT if maximum is None else maximum
    if image.height <= limit:
        return image
    width = max(1, round(image.width * limit / image.height))
    return image.resize((width, limit), Image.LANCZOS)


# ---------------------------------------------------------------------------------------------------
# The eight poses plus a portrait
# ---------------------------------------------------------------------------------------------------
# How each pose is derived from the standing image. Real art replaces these; the point is that every
# pose EXISTS so the fallback chain is exercised and the game reads correctly.
POSE_RECIPES = {
    # basic is the source itself, untouched.
    "basic": lambda image: image,
    # combat stands in as basic until a side-facing drawing replaces it. A real <name>-combat drawing
    # dropped into the output folder wins under the manifest rule, exactly as any other art pass does.
    "combat": lambda image: image,
    # damaged: knocked back and reddened.
    "damaged": lambda image: adjust(tint(lean(image, -7, 0.0), (200, 60, 50), 0.30), brightness=1.08),
    # offense: leaning into a swing. SESSION 35 dropped the mirror this used to add as a cheap second
    # frame: once art faces sideways (the `combat` stance) and the engine flips sprites by side
    # (honeycomb.art.spriteTransform), a mirrored attack pose turns the fighter away from the enemy it
    # is hitting. A deeper lean carries the beat instead, and it reads the same on front-facing art.
    "offense": lambda image: lean(image, 9, 0.03),
    # passive: a smaller, calmer lift, for skills and gestures.
    "passive": lambda image: lean(image, 2, 0.015),
}

# The hurt tier is the healthy tier, worn down, before the pose recipe is applied.
def to_hurt(image):
    return blotches(adjust(image, brightness=0.86, saturation=0.78), 12, 0.05, (135, 18, 22), 29)


# WHAT AN ORDINARY ENEMY GETS (2026-09-21). Noodle: "Basic combat sprites use -combat. Ordinary enemies
# should have -combat and -offense, that's it." The game asks an enemy for nothing else
# (honeycomb.art.enemySpriteChain), so nothing else is written. Until this date the generator wrote the
# full eleven-file character set into every enemy folder, which is where the pile of redundant enemy
# images came from each time it was cleared. Suite block [126] fails if an ordinary enemy folder holds
# any other file.
ENEMY_FILES = {"1-combat.webp", "1-offense.webp"}

# WHAT A CHARACTER OUTFIT GETS (2026-09-22). Noodle's image list names a backup for every picture, and
# only these are pictures of their own: the portrait, and the tilted stand-ins for the healthy action
# poses ("1-damaged ... backup: 1-basic tilted and filtered red", "1-offense ... backup: 1-basic tilted,
# no filter", and the gentler lean for 1-passive). Every other backup is a step in the game's own chain
# (honeycomb.art.spriteChain): 2- falls to 1-, 3- to 2-, 1-combat and 1-broken to 1-basic, exposed to
# 2-combat. So no hurt tier and no exposed are written any more -- a generated 2-combat would stand in
# FRONT of a real 1-combat in that chain and show the old art instead of the new.
CHARACTER_FILES = {"0-portrait.webp", "1-basic.webp", "1-damaged.webp", "1-offense.webp", "1-passive.webp"}


def build_pose_set(standing, *folder_parts, portrait=None, exposed=False, only=None, bare_beside_real_combat=False):
    """Writes 0-portrait plus every tier and pose for one outfit or enemy variant.

    `only` is a set of file names: given, nothing outside it is written (see ENEMY_FILES).

    Skips any file a previous run did not claim -- that means real art has replaced the placeholder,
    and overwriting it would destroy an art pass. `portrait` is a finished crop; omitted, the character
    head crop is used. `exposed` also writes the Exposed cut-in's own picture for the outfit.
    """
    folder_path = os.path.join(ART, *folder_parts)
    os.makedirs(folder_path, exist_ok=True)
    existing = set(os.listdir(folder_path)) if os.path.isdir(folder_path) else set()
    claimed = set(read_manifest(folder_path))
    written = []
    kept = []

    # An enemy whose `1-combat` is real art gets NO generated files beside it. A generated `1-offense` is
    # cut from the old stand-in drawing, so the enemy would turn into a different creature every time it
    # attacked. The game falls back to `1-combat` for the attack until a real `1-offense` is drawn.
    # ENEMIES ONLY (`bare_beside_real_combat`): a character's tilted stand-ins are Noodle's named backups
    # and are wanted beside her real art.
    real_combat = bare_beside_real_combat and "1-combat.webp" in existing and "1-combat.webp" not in claimed

    def emit(image, name):
        if only is not None and (name not in only or real_combat):
            return
        # Present but unclaimed = real art. Leave it, and leave it out of the new manifest.
        if FORCE is False and name in existing and name not in claimed:
            kept.append(name)
            return
        save(image, *(folder_parts + (name,)))
        written.append(name)

    # The portrait crops from the FULL-RESOLUTION source before the cap, so the face stays sharp.
    emit(head_crop(standing, PORTRAIT_SIZE) if portrait is None else portrait, "0-portrait.webp")
    standing = cap_height(standing)
    tier_sources = {1: standing, 2: to_hurt(standing)}
    for tier in TIERS:
        for pose in POSES:
            emit(POSE_RECIPES[pose](tier_sources[tier]), "%d-%s.webp" % (tier, pose))
    if exposed:
        emit(exposed_recipe(tier_sources[2]), "exposed.webp")

    write_manifest(folder_path, written)
    return written, kept


# THE EXPOSED CUT-IN'S OWN PICTURE (session 21). One per outfit, used by nothing else: the hurt
# sprite pushed toward the exposure rose so the cut-in reads as its own moment rather than a second
# boss-health warning. A hand-drawn exposed.png beside the target wins under the usual manifest rule.
EXPOSED_TINT = (255, 76, 110)
EXPOSED_TINT_STRENGTH = 0.34


def exposed_recipe(image):
    return adjust(tint(image, EXPOSED_TINT, EXPOSED_TINT_STRENGTH), brightness=1.04, saturation=1.18)


# ---------------------------------------------------------------------------------------------------
# Content tables -- mirror the JS content files
# ---------------------------------------------------------------------------------------------------
# WHERE A CHARACTER'S SOURCE LIVES, when it is not _source/characters/<folder> (session 35). Every
# character before Anastasia arrived as one flat drawing named after its folder. Hers arrived per pose
# in _source/chess/, so her standing art is named here and the per-pose files are dropped straight into
# the output folder, where the manifest rule protects them.
CHARACTER_SOURCES = {
    "chess": dict(kind="chess", source="chess1V-basic-a"),
}


def character_source(folder, source_stem=None):
    entry = CHARACTER_SOURCES.get(folder, {})
    return load_source(entry.get("kind", "characters"),
                       entry.get("source", folder if source_stem is None else source_stem))


# character art folder -> its outfits. `None` recipe means the source unaltered.
CHARACTER_OUTFITS = {
    # THE CHESSMASTER (session 35). One outfit so far: chess1V is Grandmaster, her default. Her basic,
    # combat, offense and passive poses are drawn and live unclaimed in the output folder; only the
    # damaged pose and the hurt tier are generated.
    "chess": [
        ("default", None),
    ],
    "knight": [
        ("default", None),
        # Session 8: one outfit per sister mechanic (MECHANICS-01.md). The six before them were retired in
        # session 9 and their folders removed.
        ("siegeplate", dict(hue=20, brightness=0.9, saturation=1.25)),
        ("bastion", dict(hue=205, brightness=1.0, saturation=0.55)),
        ("almoner", dict(hue=38, brightness=1.15, saturation=1.1)),
    ],
    "necro": [
        ("default", None),
        ("rotsinger", dict(hue=-85, brightness=0.88, saturation=1.1)),
        ("sporemother", dict(hue=22, brightness=1.1, saturation=1.3)),
        ("nightshade", dict(hue=230, brightness=0.85, saturation=1.2)),
    ],
    "vamp": [
        ("default", None),
        ("huntress", dict(hue=100, brightness=0.9, saturation=0.9)),
        ("crimsonCovenant", dict(hue=-20, brightness=0.8, saturation=1.5)),
        ("bloodSaint", dict(hue=190, brightness=1.2, saturation=0.6)),
    ],
    # Session 8: the three new characters (MECHANICS-01.md, part 6).
    "lancer": [
        ("default", None),
        ("vanguardPlume", dict(hue=28, brightness=1.05, saturation=1.25)),
        ("marshal", dict(hue=200, brightness=0.9, saturation=0.8)),
        #Session 25 added Cinder's `ashfall` but did not add it here, so wearing it 404d and fell back to
        #the default portrait (found round 07).
        ("ashfall", dict(hue=-25, brightness=0.85, saturation=0.7)),
    ],
    "priest": [
        ("default", None),
        # Session 9: Clemence's kit was rebuilt around breaking; her outfits with it.
        ("devotee", dict(hue=150, brightness=1.05, saturation=0.7)),
        ("ecstatic", dict(hue=-30, brightness=0.9, saturation=1.35)),
        ("abbess", dict(hue=200, brightness=0.95, saturation=0.6)),
    ],
    "seer": [
        ("default", None),
        ("hedgeWitch", dict(hue=90, brightness=1.0, saturation=0.9)),
        ("grifter", dict(hue=-60, brightness=0.95, saturation=1.2)),
        #Session 25 renamed Cassadora's `archivist` to `soothsayer` but left the generator naming the old
        #folder, so wearing Soothsayer requested two 404s and fell back to the default portrait. The list
        #matches the live outfits now (found round 07).
        ("soothsayer", dict(hue=250, brightness=0.9, saturation=0.75)),
    ],
}

# enemy art folder -> its own drawing in _source/enemies, and an optional portrait crop.
#
# THE CANVAS IS THE SCALE. The game draws a sprite at the stage's height, so how large an enemy reads is
# how much of its canvas it fills -- the sources share one 832x1216 canvas with each figure drawn at its
# size (smol is small in it, the brute fills it). The canvas is therefore never trimmed.
#
# `portrait` places the square face crop as fractions of the canvas: centre x, top y, and box width.
# Omitted, the crop is taken off the top of the figure's own outline (portrait_crop).
# Celestial -> Infernal, as one recipe so every piece is recoloured identically.
INFERNAL_RECIPE = dict(hue=150, brightness=0.72, saturation=1.35)

ENEMY_SOURCES = {
    "sporeling": dict(source="smol"), # Really wants a better-fit image, but is waiting for enemy scaling
    "capBrute": dict(source="brute"),
    "gloomWisp": dict(source="caster"),
    "hollowKnight": dict(source="warrior"),
    # A throne and tentacles, landscape: her outline is no guide to her face, so it is placed by hand.
    "matriarch": dict(source="matriarch", portrait=dict(x=0.482, y=0.167, box=0.21)),
    # The second boss and the enemies beside him (session 16). Every one of these is drawn on the shared
    # 832x1216 canvas except the Juggernaut, whose source is square; the canvas is the scale either way.
    "juggernaut": dict(source="juggernaut"),
    "gardener": dict(source="gardener"),
    "sage": dict(source="sage"),
    "alchemist": dict(source="alchemist"),
    "shield": dict(source="shield"),
    "scavenger": dict(source="scavenger"),
    # THE CHESSMASTER'S GOLEMS (session 35). Drawn per piece rather than hue-shifted from one source, so
    # each carries its own file under _source/chess/ and `kind` points load_source at that folder. They
    # are enemy-table entities that stand on EITHER side -- summoned by Anastasia, or fought in her
    # unlock gauntlet -- which is what forced side-aware sprite flipping (honeycomb-art.js).
    # Infernal pieces will arrive as the same stems with "Infer" in place of "Celes".
    "celestialPawn": dict(kind="chess", source="pawnCeles-basic"),
    "celestialKnight": dict(kind="chess", source="knightCeles-basic"),
    "celestialBishop": dict(kind="chess", source="bishopCeles-basic"),
    "celestialRook": dict(kind="chess", source="rookCeles-basic"),
    # Her crown sits above a face an outline crop cuts off, and her staff widens the figure box.
    "celestialQueen": dict(kind="chess", source="queenCeles-basic", portrait=dict(x=0.61, y=0.145, box=0.38)),
    # A castle-behemoth: no feet, and no face where an outline would look for one.
    "celestialKing": dict(kind="chess", source="kingCeles-basic", portrait=dict(x=0.56, y=0.15, box=0.44)),

    # `offense_from_drawing` (2026-09-22, Noodle: "please do have the generator make new infernal tilted
    # offense images"): once an Infernal piece's own `1-combat` is drawn, its `1-offense` is the offense
    # tilt of THAT drawing, not of the recoloured Celestial stand-in. See build_enemies.
    # THE INFERNAL SET, standing in on the Celestial drawings until its own arrive. White marble and
    # blue gems pushed round to charred basalt and ember: the hue turn does the colour, the brightness
    # drop does the char, and the saturation lift keeps the embers from going muddy. Swap `source` for
    # the real stems -- same names with "Infer" for "Celes" -- and drop the recipe, nothing else.
    "infernalPawn": dict(kind="chess", source="pawnCeles-basic", recipe=INFERNAL_RECIPE, offense_from_drawing=True),
    "infernalKnight": dict(kind="chess", source="knightCeles-basic", recipe=INFERNAL_RECIPE, offense_from_drawing=True),
    "infernalBishop": dict(kind="chess", source="bishopCeles-basic", recipe=INFERNAL_RECIPE, offense_from_drawing=True),
    "infernalRook": dict(kind="chess", source="rookCeles-basic", recipe=INFERNAL_RECIPE, offense_from_drawing=True),
    "infernalQueen": dict(kind="chess", source="queenCeles-basic", recipe=INFERNAL_RECIPE, offense_from_drawing=True,
                          portrait=dict(x=0.61, y=0.145, box=0.38)),
    "infernalKing": dict(kind="chess", source="kingCeles-basic", recipe=INFERNAL_RECIPE, offense_from_drawing=True,
                         portrait=dict(x=0.56, y=0.15, box=0.44)),

    # ---------------------------------------------------------------------------------------------
    # THE SESSION-34 ROSTER (rework/ENEMIES-01.md), recoloured off the drawing each one stands on.
    #
    # They used to share their stand-in's folder outright, via `artFolder` on the enemy entry -- so a
    # Puffcap and a Sporeling, or a Mold Leech and a Gloom Wisp, were the SAME PICTURE on the board.
    # Noodle, FEEDBACK-08: "The placeholder enemy sprites from that session are very confusing since
    # they're the same [...] a hue-shifted or rescaled existing enemy image would do wonders."
    #
    # Each now owns a folder and a recipe picked from its sidecar tags in ENEMIES-01 s5, so the roster
    # reads as thirteen creatures at a glance. SIZE is not here: the enemy table's own
    # `presentation.scale` already sets how tall each stands, and doing it twice would compound.
    # Dropping the real drawing in replaces the placeholder with no code change, as ever.
    #
    # Region 1 -- the Upper Catacombs, myconid and fungal fauna.
    # A swollen puffball: paler and washed out beside the Sporeling it grew from.
    "puffcap": dict(source="smol", recipe=dict(hue=-35, brightness=1.28, saturation=0.22)),
    # Green mold over something slick.
    "moldLeech": dict(source="caster", recipe=dict(hue=-160, brightness=0.82, saturation=1.30)),
    # White threads and grey flesh: the Sage, drained of its colour.
    "moldshaper": dict(source="sage", recipe=dict(hue=55, brightness=0.95, saturation=0.70)),
    # A corpse wearing mushrooms; grey skin under rust.
    "cordycepsHusk": dict(source="warrior", recipe=dict(hue=80, brightness=0.70, saturation=0.45)),
    # Bioluminescent pink: the brightest thing in the region.
    "glowMoth": dict(source="caster", recipe=dict(hue=50, brightness=1.18, saturation=1.35)),

    # Region 2 -- the Flooded Vault, fauna first and everything waterlogged.
    # Mud-caked shell and algae.
    "siltCrawler": dict(source="scavenger", recipe=dict(hue=70, brightness=0.80, saturation=0.75)),
    # Dark green and wet, rising out of the water.
    "mireEel": dict(source="caster", recipe=dict(hue=-100, brightness=0.62, saturation=1.15)),
    # Warty and mossy: the Brute gone amphibian.
    "bogToad": dict(source="brute", recipe=dict(hue=90, brightness=0.85, saturation=0.90)),
    # Soaked scrap and blue sparks.
    "drownedSalvager": dict(source="scavenger", recipe=dict(hue=150, brightness=0.75, saturation=0.85)),
    # A translucent bell with a lit core.
    "lanternJelly": dict(source="caster", recipe=dict(hue=-95, brightness=1.20, saturation=1.20)),

    # Elites and bosses.
    # Plate polished where the Hollow Knight's is rusted.
    "hollowChampion": dict(source="warrior", recipe=dict(hue=200, brightness=1.18, saturation=0.45)),
    # The Gardener's superior: greener, and in bloom.
    "headGardener": dict(source="gardener", recipe=dict(hue=90, brightness=1.02, saturation=1.45)),
    # Drowned, barnacled and counting.
    "tallyman": dict(source="sage", recipe=dict(hue=175, brightness=0.80, saturation=0.80)),
}

# How much of the busiest row or column must be opaque for it to count as FIGURE when reading an
# outline. Stray specks in a source canvas (smol has several) would otherwise widen it to the canvas.
PORTRAIT_OUTLINE_FLOOR = 0.04
PORTRAIT_OPAQUE_ALPHA = 128
# Every source drawing now belongs to an enemy: smol, brute, caster, warrior, matriarch, juggernaut,
# gardener, sage, alchemist, shield and scavenger are all mapped in ENEMY_SOURCES above.


def figure_outline(image):
    """The box the figure itself fills: rows and columns carrying at least PORTRAIT_OUTLINE_FLOOR of the
    busiest one's opaque pixels, so a few stray specks do not count."""
    width, height = image.size
    mask = image.getchannel("A").point(lambda value: 255 if value >= PORTRAIT_OPAQUE_ALPHA else 0)
    pixels = mask.load()
    column_counts = [0] * width
    row_counts = [0] * height
    for y in range(height):
        for x in range(width):
            if pixels[x, y]:
                column_counts[x] += 1
                row_counts[y] += 1

    def span(counts):
        floor = max(counts) * PORTRAIT_OUTLINE_FLOOR
        filled = [index for index, count in enumerate(counts) if count > floor]
        return (filled[0], filled[-1] + 1) if filled else (0, len(counts))

    left, right = span(column_counts)
    top, bottom = span(row_counts)
    return (left, top, right, bottom)


def portrait_crop(image, size, placement=None):
    """A square face crop for an enemy. Sources vary in shape, so the default reads the figure's outline:
    a box as wide as the figure (never taller than it), from the figure's top."""
    width, height = image.size
    if placement is not None:
        box = int(width * placement["box"])
        left = int(width * placement["x"] - box / 2)
        top = int(height * placement["y"])
    else:
        bbox = figure_outline(image)
        figure_width = bbox[2] - bbox[0]
        figure_height = bbox[3] - bbox[1]
        box = min(figure_width, figure_height)
        left = (bbox[0] + bbox[2]) // 2 - box // 2
        top = bbox[1]
    cropped = image.crop((left, top, left + box, top + box))
    return cropped.resize((size, size), Image.LANCZOS)


def apply_recipe(image, recipe):
    if recipe is None:
        return image
    result = shift_hue(image, recipe.get("hue", 0))
    result = adjust(result, brightness=recipe.get("brightness", 1.0),
                    saturation=recipe.get("saturation", 1.0))
    blot = recipe.get("blot")
    if blot:
        result = blotches(result, blot["count"], blot["radius"], blot["color"], blot["seed"])
    scale = recipe.get("scale", 1.0)
    if scale != 1.0:
        result = result.resize((max(1, int(image.width * scale)), max(1, int(image.height * scale))),
                               Image.LANCZOS)
    return result



# ---------------------------------------------------------------------------------------------------
# Art owed: the sidecar packs
# ---------------------------------------------------------------------------------------------------
# FEEDBACK-08: "Please add the keywords/art tag lists as .txt sidecar files alongside pngs in some
# folder for me to get to later."
#
# One folder, one pair per enemy whose drawing is still owed: `<enemy>.png` (the placeholder that is
# on the board right now, full size, as a PNG to paint over or feed to ControlNet) and `<enemy>.txt`
# (the prompt, in the same shape as the hand-written refs in refsPNG/enemies -- a positive line, then
# the shared negative prompt).
#
# It is its OWN folder rather than refsPNG/enemies, which holds real reference drawings: mixing
# generated stand-ins in with them would make "which of these is real art" unanswerable.
#
# Tags are ENEMIES-01 s5, verbatim. The shared negative prompt is the one on alchemist.txt, read from
# that file rather than copied, so there is one copy of it in the project.
ART_OWED_DIR = os.path.join(SOURCE_DIR, "refsPNG", "enemiesOwed")
NEGATIVE_SOURCE = os.path.join(SOURCE_DIR, "refsPNG", "enemies", "alchemist.txt")

ART_OWED_TAGS = {
    "puffcap": "fantasy, enemy, myconid, fungal fauna, full body, white background, solo, puffball mushroom, round body, swollen, bloated, spore sacs, tiny legs, no arms, cracked cap, glowing spores, dotted eyes, chibi, about to burst",
    "moldLeech": "fantasy, enemy, leech, giant leech, fungal fauna, full body, white background, solo, segmented body, slimy, mold patches, round sucker mouth, teeth ring, no eyes, green mold, glistening, coiled",
    "moldshaper": "fantasy, enemy, myconid, fungal fauna, full body, white background, solo, mushroom hat, hooded robe, mold-covered robe, holding lump of mycelium, shaping mold, white threads, hyphae, grey body, solid eyes, no mouth, purple mushrooms",
    "cordycepsHusk": "fantasy, enemy, zombie adventurer, cordyceps, fungal growth from back, mushroom stalks from shoulders, full body, white background, solo, ragged leather armor, rusted sword, hunched, blank eyes, spores, infected, grey skin",
    "glowMoth": "fantasy, enemy, moth, giant moth, fungal fauna, full body, white background, solo, fluffy thorax, mushroom cap on head, glowing wing spots, bioluminescent, pink pollen, feathered antennae, big eyes, hovering",
    "siltCrawler": "fantasy, enemy, crab, river crab, full body, white background, solo, mud-caked shell, barnacles, algae, big claw, small claw, eyestalks, armored, low stance",
    "mireEel": "fantasy, enemy, eel, giant eel, full body, white background, solo, rising from water, coiled body, slick skin, dark green, fins, gaping jaw, needle teeth, glowing eyes, water drips",
    "bogToad": "fantasy, enemy, toad, giant toad, full body, white background, solo, fat, warty skin, moss, mushrooms growing on back, long tongue, wide mouth, heavy lidded eyes, sitting, mud",
    "drownedSalvager": "fantasy, enemy, kobold, full body, white background, solo, soaked, scrap armor, road sign shield, spear with car battery strapped on, wires, sparks, goggles, diving mask, reptile, scales, tail",
    "lanternJelly": "fantasy, enemy, jellyfish, floating, full body, white background, solo, translucent bell, glowing core, lantern light, trailing tentacles, stinging tendrils, pink glow, bioluminescent, no face",
    "hollowChampion": "fantasy, enemy, myconid, fungal fauna, full body, white background, solo, mushroom hat, tall, heavy plate armor, tattered cape, greatsword, dueling stance, en garde, solid eyes, no mouth, battle-worn, large",
    "headGardener": "fantasy, enemy, myconid, fungal fauna, boss, full body, white background, solo, large, mushroom head, flower crown, moss robe, gardening shears, watering can, basket of puffballs, roots for feet, vines, green eyes, solid eyes, garden around feet",
    "tallyman": "fantasy, enemy, boss, full body, white background, solo, tall, thin, robed figure, abacus, giant ledger book, quill, spectacles, drowned, dripping, barnacles, chains of coins, hollow eyes, counting, candle on hat",
}


def shared_negative_prompt():
    """The one negative prompt the refs share, read from the file that holds it."""
    path = art_path(NEGATIVE_SOURCE)
    if not os.path.exists(path):
        return None
    for line in io.open(path, encoding="utf-8").read().splitlines():
        if line.startswith("Negative prompt:"):
            return line
    return None


def build_art_owed_sidecars():
    """A png + txt pair per enemy still waiting for its drawing."""
    print("Art owed (png + txt pairs):")
    folder = art_path(ART_OWED_DIR)
    os.makedirs(folder, exist_ok=True)
    negative = shared_negative_prompt()
    for enemy, tags in ART_OWED_TAGS.items():
        entry = ENEMY_SOURCES.get(enemy)
        if entry is None:
            print("  %s: not in ENEMY_SOURCES, skipped" % enemy)
            continue
        standing = apply_recipe(load_source(entry.get("kind", "enemies"), entry["source"]), entry.get("recipe"))
        standing.save(os.path.join(folder, enemy + ".png"))
        text = tags if negative is None else tags + "\n" + negative
        io.open(os.path.join(folder, enemy + ".txt"), "w", encoding="utf-8").write(text + "\n")
        print("  %s.png + %s.txt" % (enemy, enemy))


def real_basic(character, outfit):
    """The outfit's DRAWN 1-basic, or None. Drawn means present and not on the folder's manifest."""
    return real_image("characters", character, outfit, "1-basic.webp")


def build_characters():
    print("Characters:")
    for character, outfits in CHARACTER_OUTFITS.items():
        # The stand-ins are cut from the REAL standing drawing once there is one (2026-09-22), so a tilted
        # 1-offense shows the character as she is drawn now rather than her first reference picture. An
        # alternate outfit with no drawing of its own is still the default's, recoloured by its recipe.
        default_basic = real_basic(character, "default")
        standing = default_basic if default_basic is not None else character_source(character)
        for outfit, recipe in outfits:
            # An alt outfit with no drawing of its own is a recoloured copy of the default. See build_outfit_copies.
            if outfit != "default" and not has_real_image("characters", character, outfit):
                written = build_outfit_copies(character, outfit, recipe)
                print("  characters/%s/%s  (%d recoloured copies of default)" % (character, outfit, len(written)))
                continue
            # The outfit has art of its own, so none of its files is a copy of a drawing.
            write_copies_list(os.path.join(ART, "characters", character, outfit), [])
            own = real_basic(character, outfit)
            source = own if own is not None else apply_recipe(standing, recipe)
            written, kept = build_pose_set(source, "characters", character, outfit, only=CHARACTER_FILES)
            note = "" if not kept else "  [%d real: %s]" % (len(kept), ", ".join(sorted(kept)))
            print("  characters/%s/%s  (%d generated)%s" % (character, outfit, len(written), note))


def has_real_image(*folder_parts):
    """Whether a folder holds any picture that is not on its manifest, which means somebody drew it."""
    folder_path = os.path.join(ART, *folder_parts)
    if not os.path.isdir(folder_path):
        return False
    claimed = set(read_manifest(folder_path))
    return any(name.endswith(".webp") and name not in claimed for name in os.listdir(folder_path))


# An alt outfit with no drawing of its own gets every default picture under the same name, through its
# colour recipe. The PNG original is recoloured when there is one, then scaled to the game's size.
# An alt with a real drawing gets the usual tilted stand-ins instead (build_pose_set).
OUTFIT_COPY_SHAPE_TOLERANCE = 0.01


def build_outfit_copies(character, outfit, recipe):
    default_folder = os.path.join(ART, "characters", character, "default")
    outfit_folder = os.path.join(ART, "characters", character, outfit)
    os.makedirs(outfit_folder, exist_ok=True)
    default_claimed = set(read_manifest(default_folder))
    written = []
    copied_drawings = []
    for name in sorted(os.listdir(default_folder)):
        if not name.endswith(".webp"):
            continue
        game_copy = Image.open(os.path.join(default_folder, name)).convert("RGBA")
        original_path = os.path.join(PNG_ARCHIVE, "characters", character, "default", name[:-len(".webp")] + ".png")
        original = Image.open(original_path).convert("RGBA") if os.path.exists(original_path) else None
        # An original of another SHAPE was re-canvassed on its way into the game; scaling it would stretch
        # the figure, so the game's own copy is recoloured instead.
        if original is not None and abs(original.width / original.height - game_copy.width / game_copy.height) < OUTFIT_COPY_SHAPE_TOLERANCE:
            source = apply_recipe(original, recipe)
            if source.size != game_copy.size:
                source = source.resize(game_copy.size, Image.LANCZOS)
        else:
            source = apply_recipe(game_copy, recipe)
        save(source, "characters", character, outfit, name)
        written.append(name)
        if name not in default_claimed:
            copied_drawings.append(name)
    write_manifest(outfit_folder, written)
    write_copies_list(outfit_folder, copied_drawings)
    return written


# The copies made from a real drawing. generate-sprite-metrics.js reads this list so the game does not
# treat them as stand-ins (the Broken tint goes on stand-ins only).
COPIES_NAME = ".copies.txt"
COPIES_HEADER = (
    "# Files in this folder that generate-placeholder-art.py copied from a DRAWING in the default outfit,\n"
    "# recoloured. They are on .generated.txt too; this list only tells the game they are not stand-ins.\n"
)


def write_copies_list(folder_path, names):
    path = os.path.join(folder_path, COPIES_NAME)
    if not names:
        if os.path.exists(path):
            os.remove(path)
        return
    with io.open(path, "w", encoding="utf-8") as handle:
        handle.write(COPIES_HEADER)
        for name in sorted(names):
            handle.write(name + "\n")


def real_image(*parts):
    """A game file that is present and NOT on its folder's manifest (a drawing), as RGBA, or None."""
    folder_path = os.path.join(ART, *parts[:-1])
    path = os.path.join(ART, *parts)
    if not os.path.exists(path) or parts[-1] in set(read_manifest(folder_path)):
        return None
    return Image.open(path).convert("RGBA")


def build_enemies(flagged_only=False):
    print("Enemies:")
    for enemy, entry in ENEMY_SOURCES.items():
        # AN ATTACK TILTED FROM THE ENEMY'S OWN DRAWING (`offense_from_drawing`). The generic rule below
        # writes nothing beside a drawn `1-combat`, because a tilt of the OLD stand-in would show a
        # different creature on every attack. A tilt of the drawing itself is the same creature, so a
        # flagged entry gets exactly that: `1-offense`, unless its offense is drawn too.
        drawing = real_image("enemies", enemy, "default", "1-combat.webp") if entry.get("offense_from_drawing") else None
        if drawing is not None:
            written, kept = build_pose_set(drawing, "enemies", enemy, "default", only={"1-offense.webp"})
            print("  enemies/%s/default  (offense tilted from its drawing: %d generated%s)"
                  % (enemy, len(written), "" if not kept else ", kept " + ", ".join(sorted(kept))))
            continue
        if flagged_only:
            continue
        # A `recipe` recolours the source, exactly as an outfit does for a character. The Infernal
        # pieces are the Celestial drawings run through one until their own art arrives -- the
        # tinted-placeholder path the project has used since session 8.
        standing = apply_recipe(load_source(entry.get("kind", "enemies"), entry["source"]), entry.get("recipe"))
        portrait = portrait_crop(standing, PORTRAIT_SIZE, entry.get("portrait"))
        written, kept = build_pose_set(standing, "enemies", enemy, "default", portrait=portrait, only=ENEMY_FILES,
                                       bare_beside_real_combat=True)
        note = "" if not kept else "  [%d real: %s]" % (len(kept), ", ".join(sorted(kept)))
        print("  enemies/%s/default  (%d generated)%s" % (enemy, len(written), note))


# ---------------------------------------------------------------------------------------------------
# Card art
# ---------------------------------------------------------------------------------------------------
# Crop centres are a fraction of the SOURCE height (a 1408x2816 full body), so 0.00 is above the head
# and 1.00 is the soles. Values stay high on purpose: a card is read at thumbnail size in a fanned
# hand, and a face identifies its owner where a mid-body crop does not.
CARD_ART_RECIPES = [
    ("brienne-strike", "knight", 0.11, (200, 90, 60), "wide"),
    ("brienne-guard", "knight", 0.15, (70, 120, 200), "wide"),
    ("brienne-bulwark", "knight", 0.13, (70, 140, 190), "wide"),
    ("brienne-riposte", "knight", 0.10, (210, 110, 70), "wide"),
    ("brienne-thorns", "knight", 0.20, (150, 90, 200), "tall"),
    ("brienne-rally", "knight", 0.09, (220, 170, 80), "tall"),
    ("nettle-strike", "necro", 0.10, (110, 190, 90), "wide"),
    ("nettle-wither", "necro", 0.14, (90, 170, 80), "wide"),
    ("nettle-miasma", "necro", 0.12, (80, 160, 90), "wide"),
    ("nettle-reap", "necro", 0.09, (140, 200, 90), "wide"),
    ("nettle-harvest", "necro", 0.18, (120, 200, 140), "tall"),
    ("nettle-plague", "necro", 0.22, (70, 150, 70), "tall"),
    ("severine-strike", "vamp", 0.10, (200, 70, 110), "wide"),
    ("severine-drain", "vamp", 0.13, (180, 60, 130), "wide"),
    ("severine-flurry", "vamp", 0.11, (210, 80, 100), "wide"),
    ("severine-pact", "vamp", 0.15, (160, 50, 120), "wide"),
    ("severine-exsanguinate", "vamp", 0.09, (200, 55, 90), "wide"),
    ("severine-nightfall", "vamp", 0.19, (120, 60, 180), "tall"),
    ("severine-arc", "vamp", 0.12, (190, 50, 80), "wide"),
    # Session 8: the sister mechanics' cards (MECHANICS-01.md).
    ("brienne-bash", "knight", 0.14, (200, 120, 60), "wide"),
    ("brienne-weight", "knight", 0.30, (170, 120, 70), "wide"),
    ("brienne-challenge", "knight", 0.12, (210, 80, 60), "wide"),
    ("brienne-wall", "knight", 0.24, (90, 120, 170), "tall"),
    ("brienne-tithe", "knight", 0.17, (220, 180, 80), "wide"),
    ("brienne-alms", "knight", 0.21, (230, 200, 110), "tall"),
    ("nettle-rupture", "necro", 0.16, (150, 170, 60), "wide"),
    ("nettle-infect", "necro", 0.13, (100, 180, 110), "wide"),
    ("nettle-pollen", "necro", 0.11, (200, 120, 170), "wide"),
    ("nettle-flush", "necro", 0.20, (220, 110, 180), "tall"),
    ("severine-hunt", "vamp", 0.14, (150, 60, 60), "wide"),
    ("severine-bloodlet", "vamp", 0.17, (190, 40, 70), "wide"),
    ("severine-tide", "vamp", 0.12, (150, 30, 60), "wide"),
    ("severine-transfuse", "vamp", 0.15, (220, 90, 120), "wide"),
    ("severine-verdict", "vamp", 0.21, (130, 30, 50), "tall"),
    # Session 8: the three new characters.
    ("cinder-thrust", "lancer", 0.12, (210, 90, 50), "wide"),
    ("cinder-charge", "lancer", 0.22, (230, 120, 40), "wide"),
    ("cinder-retreat", "lancer", 0.30, (150, 80, 60), "wide"),
    ("cinder-formation", "lancer", 0.16, (200, 150, 90), "wide"),
    ("cinder-comet", "lancer", 0.20, (240, 110, 30), "tall"),
    ("clemence-rebuke", "priest", 0.12, (200, 170, 110), "wide"),
    ("clemence-confess", "priest", 0.10, (220, 120, 180), "wide"),
    ("clemence-absolve", "priest", 0.16, (160, 190, 220), "wide"),
    ("clemence-martyr", "priest", 0.22, (190, 90, 120), "tall"),
    ("cassadora-bolt", "seer", 0.12, (80, 150, 230), "wide"),
    ("cassadora-hex", "seer", 0.10, (110, 90, 200), "wide"),
    ("cassadora-turncoat", "seer", 0.18, (140, 70, 170), "wide"),
    ("cassadora-fate", "seer", 0.22, (70, 110, 200), "tall"),

    # THE SHARED BROKEN CARDS, IN BOTH WINDOWS (FEEDBACK-08). A broken form now takes the shape of the
    # card it replaced, so each character's one shared broken card can be dealt into either frame -- and
    # the two windows are different shapes (3:2 against 2:3), so one picture cannot fill both. Each gets
    # a wide crop and a tall one from the same source and centre.
    #
    # They also stop borrowing another card's picture. `brienneBroken` wore Guard's art, `nettleBroken`
    # wore Wither's, and so on, which is part of why a broken card did not read as its own thing.
    ("brienne-broken", "knight", 0.15, (70, 120, 200), "wide"),
    ("brienne-broken-tall", "knight", 0.15, (70, 120, 200), "tall"),
    ("nettle-broken", "necro", 0.14, (90, 170, 80), "wide"),
    ("nettle-broken-tall", "necro", 0.14, (90, 170, 80), "tall"),
    ("severine-broken", "vamp", 0.11, (210, 80, 100), "wide"),
    ("severine-broken-tall", "vamp", 0.11, (210, 80, 100), "tall"),
    ("cassadora-broken", "seer", 0.10, (110, 90, 200), "wide"),
    ("cassadora-broken-tall", "seer", 0.10, (110, 90, 200), "tall"),
    ("cinder-broken", "lancer", 0.16, (150, 80, 60), "wide"),
    ("cinder-broken-tall", "lancer", 0.16, (150, 80, 60), "tall"),
    ("clemence-broken", "priest", 0.14, (190, 90, 120), "wide"),
    ("clemence-broken-tall", "priest", 0.14, (190, 90, 120), "tall"),
]

# Cards that belong to NOBODY -- neutral cards and curses -- must not wear a character's face.
# They used to be cropped from the party's own art, which made the Wisp curse card read as one of
# Nettle's cards (round 02, item 8). They get an abstract motif on a tinted ground instead.
ABSTRACT_CARD_RECIPES = [
    ("neutral-focus", (60, 90, 140), (16, 22, 40), "spiral", "wide"),
    ("neutral-tonic", (50, 120, 90), (14, 34, 26), "fire", "wide"),
    ("neutral-warcry", (130, 110, 60), (36, 30, 14), "crossed", "wide"),
    ("neutral-whetted", (120, 120, 140), (30, 30, 40), "crossed", "wide"),
    ("neutral-improvise", (90, 70, 130), (24, 18, 36), "question", "wide"),
    ("neutral-hedge", (110, 90, 50), (30, 24, 12), "arch", "tall"),
    ("curse-dread", (54, 50, 62), (10, 8, 14), "eye", "wide"),
    ("curse-wisp", (90, 110, 140), (14, 18, 30), "wisp", "wide"),
]

# Matches honeycomb.tuning.art.cardFrame: the horizontal window is 3:2, the vertical roughly 2:3.
CARD_WINDOW = {"wide": (768, 512), "tall": (544, 824)}


def crop_to_ratio(image, target_width, target_height, centre_fraction):
    target_ratio = target_width / target_height
    width, height = image.size
    crop_height = int(width / target_ratio)
    if crop_height > height:
        crop_height = height
        crop_width = int(height * target_ratio)
    else:
        crop_width = width
    centre_y = int(height * centre_fraction)
    top = max(0, min(height - crop_height, centre_y - crop_height // 2))
    left = (width - crop_width) // 2
    return image.crop((left, top, left + crop_width, top + crop_height)).resize(
        (target_width, target_height), Image.LANCZOS)


def build_card_art():
    print("Card art:")
    sources = {stem: load_source("characters", stem) for stem in SOURCE_CHARACTERS}
    for stem, source_stem, centre, colour, ratio in CARD_ART_RECIPES:
        width, height = CARD_WINDOW[ratio]
        art = crop_to_ratio(sources[source_stem], width, height, centre)
        # The source art is cut out; a card window showing the page through it reads as a hole, so it
        # is flattened onto a tinted ground.
        ground = Image.new("RGBA", (width, height), (0, 0, 0, 255))
        draw = ImageDraw.Draw(ground)
        for row in range(height):
            blend = row / max(1, height - 1)
            draw.line([(0, row), (width, row)], fill=(
                int(colour[0] * (0.30 + 0.30 * (1 - blend))),
                int(colour[1] * (0.30 + 0.30 * (1 - blend))),
                int(colour[2] * (0.30 + 0.30 * (1 - blend))), 255))
        save(adjust(Image.alpha_composite(ground, art), brightness=1.05, contrast=1.05),
             "cards", "art", stem + ".webp")
    for stem, top, bottom, motif, ratio in ABSTRACT_CARD_RECIPES:
        width, height = CARD_WINDOW[ratio]
        image = vertical_gradient((width, height), top, bottom)
        image = add_glow(image, [(0.5, 0.45)], tuple(min(255, c * 2) for c in top), 0.32, 70)
        save(draw_motif(image, motif, (255, 255, 255)), "cards", "art", stem + ".webp")
    print("  %d card illustrations, %d abstract" % (len(CARD_ART_RECIPES), len(ABSTRACT_CARD_RECIPES)))


# ---------------------------------------------------------------------------------------------------
# Backgrounds and panels
# ---------------------------------------------------------------------------------------------------
def vertical_gradient(size, top_color, bottom_color):
    image = Image.new("RGBA", size)
    draw = ImageDraw.Draw(image)
    for row in range(size[1]):
        blend = row / max(1, size[1] - 1)
        draw.line([(0, row), (size[0], row)], fill=tuple(
            int(top_color[c] + (bottom_color[c] - top_color[c]) * blend) for c in range(3)) + (255,))
    return image


def add_pillars(image, count, color, alpha, seed):
    width, height = image.size
    layer = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    state = seed
    for index in range(count):
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        centre = int(width * (index + 0.5) / count + ((state >> 8) % max(1, width // count)) - width // (count * 2))
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        half = int(width * 0.02) + int((state >> 8) % max(1, int(width * 0.035)))
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        top = int(height * 0.05) + int((state >> 8) % max(1, int(height * 0.3)))
        draw.rounded_rectangle([centre - half, top, centre + half, height], radius=half,
                               fill=color + (alpha,))
    return Image.alpha_composite(image, layer.filter(ImageFilter.GaussianBlur(width * 0.006)))


def add_glow(image, points, color, radius_fraction, alpha):
    width, height = image.size
    layer = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    radius = int(min(width, height) * radius_fraction)
    for (fx, fy) in points:
        x, y = int(width * fx), int(height * fy)
        draw.ellipse([x - radius, y - radius, x + radius, y + radius], fill=color + (alpha,))
    return Image.alpha_composite(image, layer.filter(ImageFilter.GaussianBlur(radius * 0.6)))


BACKGROUND_SIZE = (1600, 900)
BACKGROUND_RECIPES = [
    ("background-upper", (58, 40, 82), (20, 14, 32), (120, 70, 160), [(0.2, 0.55), (0.62, 0.4), (0.85, 0.62)]),
    ("background-vault", (34, 62, 78), (12, 22, 32), (60, 150, 170), [(0.3, 0.5), (0.7, 0.45)]),
    ("background-battle", (52, 34, 72), (16, 11, 26), (150, 70, 120), [(0.5, 0.6), (0.15, 0.45), (0.85, 0.45)]),
]

PANEL_SIZE = (512, 512)
PANEL_RECIPES = [
    ("preview-combat", (92, 40, 40), (28, 14, 16), "crossed"),
    ("preview-elite", (110, 32, 60), (30, 10, 20), "crossed"),
    ("preview-boss", (120, 26, 30), (26, 8, 10), "eye"),
    ("preview-event", (96, 78, 34), (28, 22, 12), "question"),
    ("preview-treasure", (120, 96, 34), (32, 26, 12), "chest"),
    ("preview-rest", (110, 62, 28), (30, 18, 10), "fire"),
    # The event pictures are real art in events/ and have no recipe here, so a --force run cannot
    # paint over them.
]


def draw_motif(image, motif, color):
    # Drawn on a layer and composited: a translucent fill drawn straight onto an RGBA image REPLACES the
    # pixels under it instead of blending, which left see-through holes where the motif should be.
    width, height = image.size
    layer = Image.new("RGBA", image.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    cx, cy = width // 2, height // 2
    unit = min(width, height)
    paint = color + (70,)
    if motif == "crossed":
        t, o = int(unit * 0.06), int(unit * 0.26)
        draw.line([cx - o, cy - o, cx + o, cy + o], fill=paint, width=t)
        draw.line([cx + o, cy - o, cx - o, cy + o], fill=paint, width=t)
    elif motif == "eye":
        r = int(unit * 0.24)
        draw.ellipse([cx - r * 1.6, cy - r, cx + r * 1.6, cy + r], outline=paint, width=int(unit * 0.045))
        draw.ellipse([cx - r * 0.45, cy - r * 0.45, cx + r * 0.45, cy + r * 0.45], fill=paint)
    elif motif == "question":
        r = int(unit * 0.2)
        draw.arc([cx - r, cy - r * 1.5, cx + r, cy + r * 0.2], start=160, end=20, fill=paint, width=int(unit * 0.055))
        draw.line([cx, cy + r * 0.1, cx, cy + r * 0.6], fill=paint, width=int(unit * 0.055))
        draw.ellipse([cx - unit * 0.035, cy + r * 0.85, cx + unit * 0.035, cy + r * 0.85 + unit * 0.07], fill=paint)
    elif motif == "chest":
        h = int(unit * 0.24)
        draw.rounded_rectangle([cx - h, cy - h * 0.55, cx + h, cy + h * 0.8], radius=int(unit * 0.03),
                               outline=paint, width=int(unit * 0.045))
        draw.line([cx - h, cy + h * 0.1, cx + h, cy + h * 0.1], fill=paint, width=int(unit * 0.04))
    elif motif == "fire":
        h = int(unit * 0.22)
        draw.polygon([(cx, cy - h * 1.3), (cx + h, cy + h * 0.6), (cx, cy + h), (cx - h, cy + h * 0.6)], outline=paint)
        draw.polygon([(cx, cy - h * 0.5), (cx + h * 0.5, cy + h * 0.6), (cx - h * 0.5, cy + h * 0.6)], fill=paint)
    elif motif == "arch":
        h = int(unit * 0.22)
        draw.arc([cx - h, cy - h, cx + h, cy + h], start=180, end=360, fill=paint, width=int(unit * 0.05))
        draw.line([cx - h, cy, cx - h, cy + h * 1.4], fill=paint, width=int(unit * 0.05))
        draw.line([cx + h, cy, cx + h, cy + h * 1.4], fill=paint, width=int(unit * 0.05))
    elif motif == "spiral":
        r = int(unit * 0.26)
        for step in range(4):
            inset = int(r * step * 0.22)
            draw.arc([cx - r + inset, cy - r + inset, cx + r - inset, cy + r - inset],
                     start=step * 90, end=step * 90 + 270, fill=paint, width=int(unit * 0.04))
    elif motif == "wisp":
        # A pale orb trailing upward: something that drifts into a deck uninvited.
        r = int(unit * 0.13)
        for ring in range(5, 0, -1):
            grow = r * (1 + ring * 0.35)
            draw.ellipse([cx - grow, cy - grow + r * 0.4, cx + grow, cy + grow + r * 0.4], fill=color + (14,))
        draw.ellipse([cx - r, cy - r + r * 0.4, cx + r, cy + r + r * 0.4], fill=color + (120,))
        draw.polygon([(cx - r * 0.7, cy), (cx, cy - r * 3.2), (cx + r * 0.7, cy)], fill=color + (60,))
    return Image.alpha_composite(image, layer.filter(ImageFilter.GaussianBlur(unit * 0.004)))


# ---------------------------------------------------------------------------------------------------
# Map backdrops -- paintings with landmarks
# ---------------------------------------------------------------------------------------------------
# A hand-placed map is anchored to a PAINTING: the region's anchors are percentages measured over the
# image. These stand-ins paint a labelled landmark at every anchor so that is visible -- a node that
# sits on its landmark proves the anchoring, and one that does not proves it broken.
#
# THE ANCHORS ARE MEASURED FROM THESE PAINTINGS, the way a real art pass works: paint first, then read
# the percentages off the image into honeycomb.regionArray. Changing a landmark here means changing the
# matching anchor there. (x, y) are percentages from the top-left.
# SESSION 17: the floors doubled, so the paintings are 3.2:1 panoramas now. A 16:9 painting could not be
# longer than the window; the map canvas takes this aspect and the viewport scrolls sideways.
MAP_BACKDROP_SIZE = (2880, 900)
MAP_BACKDROPS = [
    ("backdrop-vault-causeway", (30, 58, 74), (10, 20, 30), [
        ("Entry", 5, 50),
        ("North Pier", 11, 32), ("South Steps", 13, 70),
        ("North Walk", 18, 22), ("Sunken Hall", 20, 52), ("South Walk", 19, 82),
        ("Broken Span", 26, 30), ("Cistern Mouth", 28, 64), ("Tidepool", 27, 86),
        ("Lamp Row", 34, 24), ("Drowned Shrine", 36, 54), ("Tollhouse", 35, 84),
        ("Upper Causeway", 43, 32), ("Weir Walk", 45, 62),
        ("Fork North", 52, 24), ("Fork Mid", 54, 54), ("Fork South", 53, 82),
        ("North Rejoin", 61, 30), ("Mid Rejoin", 63, 60),
        ("High Walk", 69, 24), ("Cistern", 71, 54), ("Lower Walk", 70, 84),
        ("Deep Cut", 78, 32), ("Last Span", 80, 64),
        ("Last Dry Step", 88, 45),
        ("Cistern Gate", 95, 55),
    ]),
    ("backdrop-vault-stair", (26, 52, 70), (8, 18, 28), [
        ("Landing", 6, 60),
        ("First Flight", 12, 42), ("Spillway", 14, 80),
        ("Mid Landing", 20, 30), ("Flooded", 22, 70),
        ("Archway", 28, 24), ("Deep Cut", 30, 58), ("Alcove", 29, 86),
        ("Undercroft", 36, 36), ("Cistern", 38, 68),
        ("Stair Head", 44, 26), ("Spill Gate", 46, 58),
        ("Mid Arch", 52, 34), ("Drowned Row", 54, 72),
        ("Floodline", 60, 26), ("The Cut", 62, 60),
        ("Lamp Niche", 68, 34), ("Old Cistern", 70, 70),
        ("Archway II", 76, 32), ("Deep Cut II", 78, 64),
        ("Last Landing", 86, 50),
        ("Vault Door", 94, 55),
    ]),
    # THE SHOWCASE. Built to look nothing like a procedural map: its path climbs BACKWARDS to a lookout
    # in the top-left corner, behind where the party came in. A generated row layout can never put a
    # node there, so seeing one sitting on the Lookout is proof the painting is placing the map.
    ("backdrop-vault-showcase", (40, 34, 70), (12, 10, 24), [
        ("Gate", 6, 72),
        ("Lower Hall", 12, 82), ("Watch Stair", 14, 44),
        ("THE LOOKOUT", 7, 14), ("Midway", 20, 64),
        ("Ossuary", 26, 24), ("Floodline", 28, 80),
        ("Bridge", 35, 50),
        ("Undertow", 42, 26), ("Sink", 44, 68),
        ("Stair", 50, 44), ("Cistern", 52, 80),
        ("High Path", 58, 24), ("Low Path", 60, 62),
        ("Bridge II", 66, 40), ("Floodline II", 68, 80),
        ("Terrace", 74, 34), ("The Deep", 76, 70),
        ("Sanctum", 85, 40),
        ("Throne", 94, 64),
    ]),
]


def label_font(size):
    for candidate in (os.path.join(ROOT, "scripts", "fonts", "norwester.otf"),):
        if os.path.exists(candidate):
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def build_map_backdrops():
    print("Map backdrops:")
    width, height = MAP_BACKDROP_SIZE
    font = label_font(int(height * 0.028))
    for stem, top, bottom, landmark_array in MAP_BACKDROPS:
        image = vertical_gradient(MAP_BACKDROP_SIZE, top, bottom)
        image = add_pillars(image, 9, tuple(int(c * 0.6) for c in top), 110, 9876)
        image = add_glow(image, [(x / 100.0, y / 100.0) for _name, x, y in landmark_array],
                         tuple(min(255, int(c * 2.4)) for c in top), 0.07, 70)
        # Drawn on a layer of its own and composited, because drawing a translucent fill straight onto
        # an RGBA image REPLACES the pixels rather than blending them, and punches holes in the painting.
        layer = Image.new("RGBA", MAP_BACKDROP_SIZE, (0, 0, 0, 0))
        draw = ImageDraw.Draw(layer)
        radius = int(height * 0.045)
        for name, x, y in landmark_array:
            px, py = int(width * x / 100.0), int(height * y / 100.0)
            # A platform the node will sit on, and its name beneath it. The name clears the tallest
            # node shape -- the boss diamond reaches about 1.6x the radius below its anchor -- so a
            # larger icon never covers its own label (session 18).
            draw.ellipse([px - radius, py - radius * 0.55, px + radius, py + radius * 0.55],
                         fill=(0, 0, 0, 110), outline=(240, 216, 154, 140), width=3)
            text_width = draw.textlength(name, font=font)
            draw.text((px - text_width / 2, py + radius * 1.75), name, font=font, fill=(240, 216, 154, 190))
        save(Image.alpha_composite(image, layer).convert("RGB"), "map", stem + ".webp")
    print("  %d painted backdrops" % len(MAP_BACKDROPS))


def build_backgrounds():
    print("Backgrounds and panels:")
    for stem, top, bottom, glow, points in BACKGROUND_RECIPES:
        image = vertical_gradient(BACKGROUND_SIZE, top, bottom)
        image = add_pillars(image, 7, tuple(int(c * 0.55) for c in top), 150, 4321)
        save(add_glow(image, points, glow, 0.18, 90), "map", stem + ".webp")
    for stem, top, bottom, motif in PANEL_RECIPES:
        image = vertical_gradient(PANEL_SIZE, top, bottom)
        image = add_glow(image, [(0.5, 0.45)], tuple(min(255, c * 2) for c in top), 0.3, 60)
        save(draw_motif(image, motif, (255, 255, 255)), "map", stem + ".webp")
    print("  %d backgrounds, %d panels" % (len(BACKGROUND_RECIPES), len(PANEL_RECIPES)))


# ---------------------------------------------------------------------------------------------------
# UI frames -- nine-slice chrome for panels, windows, buttons and tabs (feedback item 21)
# ---------------------------------------------------------------------------------------------------
# The mockups frame everything in dark panels with CUT CORNERS and a thin metal trim -- gold for anything
# primary -- with a small ornament where each corner turns. CSS can cut a corner but cannot draw a trim
# along the cut, nor the ornament a real frame will carry, so frames are IMAGES: nine-slice sources the
# game stretches with `border-image`, fill and all. These stand-ins are drawn in roughly the final
# shape so an art pass can see what each file is for and replace it in place.
#
# Each frame's CUT is also its SLICE -- the pixels from each edge that stay unstretched -- and must
# match tuning.art.uiFrameArray in honeycomb-tuning.js. Change both together. Drawn at twice the size
# they are shown and saved lossless, because thin trim smears in lossy WebP.
#
# PROTECTED LIKE THE CHARACTER ART: the folder carries a manifest, and a file not listed in it (a drawn
# frame) is never overwritten.
UI_FRAME_FOLDER = ("ui", "frames")
UI_FRAMES = [
    # name,            size, cut, fill top,       fill bottom,    trim,            hairline,        ornament,        corners
    ("panel",           128, 28, (23, 17, 34),   (23, 17, 34),   (106, 82, 137),  (59, 45, 82),    (156, 143, 174), "all"),
    ("window",          160, 36, (33, 24, 48),   (23, 17, 34),   (201, 169, 97),  (106, 79, 34),   (240, 216, 154), "all"),
    ("button",           64, 16, (33, 24, 48),   (23, 17, 34),   (106, 82, 137),  (59, 45, 82),    None,            "all"),
    ("button-primary",   64, 16, (74, 54, 28),   (42, 30, 16),   (201, 169, 97),  (240, 216, 154), None,            "all"),
    ("tab",              64, 14, (16, 11, 26),   (16, 11, 26),   (59, 45, 82),    None,            None,            "top"),
    ("tab-active",       64, 14, (33, 24, 48),   (33, 24, 48),   (201, 169, 97),  None,            None,            "top"),
    # The square plate an item (relic, equipment) sits on: larger than the old round icon, and cut rather
    # than round, so a drawn item has room to be seen.
    ("plate",            96, 20, (40, 30, 56),   (18, 13, 28),   (138, 109, 59),  (74, 58, 34),    None,            "all"),
]


def frame_outline(size, cut, inset, corners):
    """The frame's outline `inset` pixels in from the edge, as a list of points. The cut shrinks as the
    outline moves in, so every inner diagonal stays parallel to the outer one.

    corners "all": a closed octagon, clockwise from the top-left cut.
    corners "top": an OPEN path for a tab -- up the left side, across the top, down the right -- with no
    bottom edge, since a tab sits on the panel it belongs to.
    """
    s = size - 1
    c = max(0.0, cut - inset * 0.414)
    i = inset
    if corners == "all":
        return [(i + c, i), (s - i - c, i), (s - i, i + c), (s - i, s - i - c),
                (s - i - c, s - i), (i + c, s - i), (i, s - i - c), (i, i + c), (i + c, i)]
    return [(i, s), (i, i + c), (i + c, i), (s - i - c, i), (s - i, i + c), (s - i, s)]


def build_ui_frames():
    print("UI frames:")
    folder = os.path.join(ART, *UI_FRAME_FOLDER)
    os.makedirs(folder, exist_ok=True)
    claimed = read_manifest(folder)
    written = []
    skipped = 0
    for name, size, cut, fill_top, fill_bottom, trim, hairline, ornament, corners in UI_FRAMES:
        file_name = name + ".webp"
        target = os.path.join(folder, file_name)
        if os.path.exists(target) and file_name not in claimed and not FORCE:
            skipped += 1
            continue
        # The fill, clipped to the outline: outside the cuts stays transparent, which is what gives an
        # element its cut corners with no clip-path (and so no clipped shadows or hover glows).
        outline = frame_outline(size, cut, 0, corners)
        fill = vertical_gradient((size, size), fill_top, fill_bottom).convert("RGBA")
        mask = Image.new("L", (size, size), 0)
        ImageDraw.Draw(mask).polygon(outline if corners == "all" else outline + [(size - 1, size - 1), (0, size - 1)], fill=255)
        image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        image.paste(fill, (0, 0), mask)
        draw = ImageDraw.Draw(image)
        outer = frame_outline(size, cut, 1, corners)
        draw.line(outer, fill=trim + (255,), width=3, joint="curve")
        if hairline is not None:
            draw.line(frame_outline(size, cut, 7, corners), fill=hairline + (255,), width=2, joint="curve")
        if ornament is not None and corners == "all":
            # A small diamond on each cut, where a drawn frame will carry its corner piece.
            r = max(3, cut // 6)
            for (ax, ay), (bx, by) in [(outer[1], outer[2]), (outer[3], outer[4]), (outer[5], outer[6]), (outer[7], outer[8])]:
                mx, my = (ax + bx) / 2.0, (ay + by) / 2.0
                draw.polygon([(mx, my - r), (mx + r, my), (mx, my + r), (mx - r, my)], fill=ornament + (255,))
        image.save(target, "WEBP", lossless=True)
        written.append(file_name)
    write_manifest(folder, written)
    print("  %d frames written, %d drawn frame(s) left untouched" % (len(written), skipped))


# ---------------------------------------------------------------------------------------------------
def stash_sources():
    """Moves the original art into _source/ on first run, so sources and output never mix."""
    moves = [("full", "characters", SOURCE_CHARACTERS)]
    for old_folder, kind, stems in moves:
        for stem in stems:
            old = os.path.join(ART, old_folder, stem + ".webp")
            new = os.path.join(ART, SOURCE_DIR, kind, stem + ".webp")
            if os.path.exists(old) and not os.path.exists(new):
                os.makedirs(os.path.dirname(new), exist_ok=True)
                shutil.copy2(old, new)
                print("  stashed %s -> %s" % (old_folder + "/" + stem, SOURCE_DIR + "/" + kind))


def read_manifest(folder_path):
    """The files a previous run wrote into this folder, or an empty list."""
    manifest = os.path.join(folder_path, MANIFEST_NAME)
    if not os.path.exists(manifest):
        return []
    with io.open(manifest, encoding="utf-8") as handle:
        return [line.strip() for line in handle
                if line.strip() and not line.startswith("#")]


def write_manifest(folder_path, names):
    with io.open(os.path.join(folder_path, MANIFEST_NAME), "w", encoding="utf-8") as handle:
        handle.write(MANIFEST_HEADER)
        for name in sorted(names):
            handle.write(name + "\n")


def clear_previous_output(roots=None):
    """Deletes only files a previous run claimed, leaving real art and stray files alone."""
    root_array = GENERATED_ROOTS if roots is None else roots
    if FORCE:
        for root_folder in GENERATED_ROOTS:
            path = os.path.join(ART, root_folder)
            if os.path.isdir(path):
                shutil.rmtree(path)
        print("  --force: previous output cleared wholesale")
        return 0
    protected = 0
    removed = 0
    for root_folder in root_array:
        root_path = os.path.join(ART, root_folder)
        if not os.path.isdir(root_path):
            continue
        for current, _dirs, files in os.walk(root_path):
            claimed = read_manifest(current)
            if not claimed:
                # No manifest: this folder was not written by the generator. Never touch it.
                protected += len([f for f in files if f != MANIFEST_NAME])
                continue
            for name in files:
                if name == MANIFEST_NAME:
                    continue
                if name in claimed:
                    os.remove(os.path.join(current, name))
                    removed += 1
                else:
                    protected += 1
    if protected:
        print("  %d file(s) not written by this script were left untouched" % protected)
    return removed


# ---------------------------------------------------------------------------------------------------
# Derived masks for the !!BROKEN!! cut-in (session 5)
# ---------------------------------------------------------------------------------------------------
# A CSS mask reads ALPHA: opaque shows, transparent hides. Noodle's brokenClawMask.webp and
# recoverBarMask.webp are built the other way round -- opaque black OUTSIDE the shape, transparent
# inside it -- because they are painted to be laid over a picture rather than used as masks.
#
# `mask-composite: exclude` would invert them at runtime, but it is Chrome 120+ and this game has to
# run in a Cordova WebView, so the complement is baked instead. These are DERIVED assets: regenerate
# them from the originals rather than editing them by hand.
BROKEN_MASK_ARRAY = [
    ("ui/broken/brokenClawMask.webp", "ui/broken/brokenClawMaskInner.webp"),
    ("ui/broken/recoverBarMask.webp", "ui/broken/recoverBarMaskInner.webp"),
]


# The cut-in portraits themselves. Brienne's is drawn (characters/knight/broken.png); the other two
# are stand-ins cut from each character's own full-body art, so every character gets the overlay while
# only one of them has real art for it. A real <folder>/broken.webp overwrites its stand-in only under
# --force, the same rule every other generated asset follows.
# Empty: every character's cut-ins come from her outfit folder (`1-broken`, `recover`), which every
# default outfit has, so the old per-character broken.webp and recover.webp were never reached and are
# no longer built. A row here brings one back.
BROKEN_PORTRAIT_ARRAY = []

# Enemies that play the cut-in (round 06, item 10). Their stand-in is cut from their own standing sprite in
# the enemies folder, since there is no flat source image for an enemy: (folder, sprite path under ART).
BROKEN_ENEMY_PORTRAIT_ARRAY = [
    ("matriarch", "enemies/matriarch/default/1-combat.webp"),
    # The second boss breaks on screen too (session 16), so he gets the same stand-in treatment.
    ("juggernaut", "enemies/juggernaut/default/1-combat.webp"),
]


def build_broken_portraits():
    print("Broken cut-in portraits:")
    for folder, sprite_relative in BROKEN_ENEMY_PORTRAIT_ARRAY:
        output_relative = "enemies/%s/broken.webp" % folder
        output_path = os.path.join(ART, *output_relative.split("/"))
        drawn_path = os.path.join(ART, "enemies", folder, "broken.png")
        if os.path.exists(drawn_path):
            save(Image.open(drawn_path).convert("RGBA"), *output_relative.split("/"))
            print("  ", output_relative, "(converted from broken.png)")
            continue
        if os.path.exists(output_path) and not FORCE:
            print("  ", output_relative, "(kept)")
            continue
        standing = Image.open(os.path.join(ART, *sprite_relative.split("/"))).convert("RGBA")
        stand_in = adjust(standing, brightness=0.92, saturation=0.55, contrast=1.05)
        stand_in = tint(stand_in, (232, 96, 190), 0.22)
        save(stand_in, *output_relative.split("/"))
        print("  ", output_relative, "(stand-in)")
    for folder, source_stem in BROKEN_PORTRAIT_ARRAY:
        output_relative = "characters/%s/broken.webp" % folder
        output_path = os.path.join(ART, *output_relative.split("/"))
        # A hand-drawn PNG beside the target is the real art: convert it rather than paint over it.
        drawn_path = os.path.join(ART, "characters", folder, "broken.png")
        if os.path.exists(drawn_path):
            save(Image.open(drawn_path).convert("RGBA"), *output_relative.split("/"))
            print("  ", output_relative, "(converted from broken.png)")
            continue
        if os.path.exists(output_path) and not FORCE:
            print("  ", output_relative, "(kept)")
            continue
        # The stand-in: the character's standing art, desaturated and pushed toward the lust palette so
        # it reads as the same moment even though the pose is wrong.
        standing = character_source(folder, source_stem)
        stand_in = adjust(standing, brightness=0.92, saturation=0.55, contrast=1.05)
        stand_in = tint(stand_in, (232, 96, 190), 0.22)
        save(stand_in, *output_relative.split("/"))
        print("  ", output_relative, "(stand-in)")


# THE RECOVERY CUT-IN'S PORTRAIT (round 05, item 4).
# > Recovery should not use the broken sprite, make placeholders for a recover.webp for each character
# > using their normal standing sprite.
# So unlike the broken stand-ins above these are NOT desaturated and NOT tinted -- the standing art as
# it is, which is the whole of what was asked for. A hand-drawn recover.png beside the target wins, the
# same rule every other generated asset follows.
def build_recover_portraits():
    print("Recovery cut-in portraits:")
    for folder, source_stem in BROKEN_PORTRAIT_ARRAY:
        output_relative = "characters/%s/recover.webp" % folder
        output_path = os.path.join(ART, *output_relative.split("/"))
        drawn_path = os.path.join(ART, "characters", folder, "recover.png")
        if os.path.exists(drawn_path):
            save(Image.open(drawn_path).convert("RGBA"), *output_relative.split("/"))
            print("  ", output_relative, "(converted from recover.png)")
            continue
        if os.path.exists(output_path) and not FORCE:
            print("  ", output_relative, "(kept)")
            continue
        save(character_source(folder, source_stem), *output_relative.split("/"))
        print("  ", output_relative, "(stand-in: the standing sprite)")


# THE EXPOSED CUT-IN'S TITLE (session 21). "EXPOSED" in the display font, white over a rose glow, on
# transparent. A hand-drawn ui/exposed/exposedText.png wins under the usual rule. UI frames and other
# ui/ assets are not part of clear_previous_output's character/enemy sweep, so this checks its own
# target and keeps a real file.
EXPOSED_TEXT_CANVAS = (1400, 420)
EXPOSED_TEXT_SIZE = 232
EXPOSED_TEXT_GLOW = (255, 52, 104)
EXPOSED_TEXT_BLUR = 30


def build_exposed_text():
    print("Exposed cut-in title:")
    output_relative = "ui/exposed/exposedText.webp"
    output_path = os.path.join(ART, *output_relative.split("/"))
    drawn_path = os.path.join(ART, "ui", "exposed", "exposedText.png")
    if os.path.exists(drawn_path):
        save(Image.open(drawn_path).convert("RGBA"), *output_relative.split("/"))
        print("  ", output_relative, "(converted from exposedText.png)")
        return
    if os.path.exists(output_path) and not FORCE:
        print("  ", output_relative, "(kept)")
        return
    width, height = EXPOSED_TEXT_CANVAS
    layer = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    font = label_font(EXPOSED_TEXT_SIZE)
    text = "EXPOSED"
    text_width = draw.textlength(text, font=font)
    draw.text(((width - text_width) / 2, height * 0.20), text, font=font, fill=(255, 246, 250, 255))
    glow = layer.filter(ImageFilter.GaussianBlur(EXPOSED_TEXT_BLUR))
    rose = Image.new("RGBA", (width, height), EXPOSED_TEXT_GLOW + (255,))
    rose.putalpha(glow.getchannel("A"))
    save(Image.alpha_composite(rose, layer), *output_relative.split("/"))
    print("  ", output_relative, "(stand-in)")


def build_broken_masks():
    print("Broken cut-in masks:")
    for source_relative, output_relative in BROKEN_MASK_ARRAY:
        source_path = os.path.join(ART, *source_relative.split("/"))
        if not os.path.exists(source_path):
            print("  MISSING", source_relative)
            continue
        source = Image.open(source_path).convert("RGBA")
        alpha = source.split()[3]
        # The complement: white where the original was transparent, transparent where it was opaque.
        inverted = ImageOps.invert(alpha)
        result = Image.merge("RGBA", (
            Image.new("L", source.size, 255),
            Image.new("L", source.size, 255),
            Image.new("L", source.size, 255),
            inverted,
        ))
        save(result, *output_relative.split("/"))
        print("  ", output_relative)


# THE LEWD SUPERTYPE'S OWN FRAME AND ICON (round 06, item 11).
# > Finally, lewd cards should have their own cardframe and icon as one of the game's supertypes.
# Stand-ins only: the shared placeholder frames pushed into the lust palette with a heart on each corner,
# and heart-red recoloured pink with a keyhole cut through it (heart-glow-pink is Regeneration's). A drawn
# .png beside a target wins, and an existing .webp is kept without --force, as with every generated asset.
LEWD_FRAME_ARRAY = [
    ("cards/frames/placeholderVertical.webp", "cards/frames/lewdVertical.webp"),
    ("cards/frames/placeholderHorizontal.webp", "cards/frames/lewdHorizontal.webp"),
]
LEWD_ICON = ("icons/heart-red.webp", "icons/type-lewd.webp")
LEWD_HUE_SHIFT_DEGREES = 295
LEWD_CORNER_HEART_FRACTION = 0.085
LEWD_CORNER_INSET_FRACTION = 0.004
LEWD_PINK = (255, 95, 210)
LEWD_KEYHOLE_COLOR = (58, 10, 40, 255)


def lewd_target_is_free(output_relative):
    output_path = os.path.join(ART, *output_relative.split("/"))
    drawn_path = output_path[:-len(".webp")] + ".png"
    if os.path.exists(drawn_path):
        save(Image.open(drawn_path).convert("RGBA"), *output_relative.split("/"))
        print("  ", output_relative, "(converted from .png)")
        return False
    if os.path.exists(output_path) and not FORCE:
        print("  ", output_relative, "(kept)")
        return False
    return True


def lewd_heart_icon():
    heart = Image.open(os.path.join(ART, *LEWD_ICON[0].split("/"))).convert("RGBA")
    pink = adjust(shift_hue(heart, -30), saturation=1.15, brightness=1.08)
    pink = tint(pink, LEWD_PINK, 0.25)
    draw = ImageDraw.Draw(pink)
    width, height = pink.size
    centre_x = width * 0.5
    circle_top = height * 0.36
    radius = width * 0.075
    draw.ellipse([centre_x - radius, circle_top, centre_x + radius, circle_top + radius * 2], fill=LEWD_KEYHOLE_COLOR)
    draw.polygon([
        (centre_x - radius * 0.55, circle_top + radius * 1.4),
        (centre_x + radius * 0.55, circle_top + radius * 1.4),
        (centre_x + radius * 1.0, circle_top + radius * 4.2),
        (centre_x - radius * 1.0, circle_top + radius * 4.2),
    ], fill=LEWD_KEYHOLE_COLOR)
    return pink


def build_lewd_card_type():
    print("Lewd supertype frame and icon:")
    heart = lewd_heart_icon()
    if lewd_target_is_free(LEWD_ICON[1]):
        save(heart, *LEWD_ICON[1].split("/"))
        print("  ", LEWD_ICON[1], "(stand-in)")
    for source_relative, output_relative in LEWD_FRAME_ARRAY:
        if not lewd_target_is_free(output_relative):
            continue
        source = Image.open(os.path.join(ART, *source_relative.split("/"))).convert("RGBA")
        frame = adjust(shift_hue(source, LEWD_HUE_SHIFT_DEGREES), saturation=1.1, brightness=1.02)
        size = int(frame.size[0] * LEWD_CORNER_HEART_FRACTION)
        inset = int(frame.size[0] * LEWD_CORNER_INSET_FRACTION)
        small = heart.resize((size, size), Image.LANCZOS)
        for corner_x in (inset, frame.size[0] - size - inset):
            for corner_y in (inset, frame.size[1] - size - inset):
                frame.alpha_composite(small, (corner_x, corner_y))
        save(frame, *output_relative.split("/"))
        print("  ", output_relative, "(stand-in)")


# DOWNSAMPLED CARD FRAMES (session 15, round 07 C). Must match tuning.art.cardFrame.frameSuffixBySize.
# The full 1992x2540 frames stay as the sources; each card size draws a copy at a share of their width.
CARD_FRAME_SIZE_SHARES = [("-small", 1 / 6), ("-medium", 1 / 3), ("-large", 1 / 2)]


def build_card_frame_sizes():
    folder = art_path("cards", "frames")
    suffixes = tuple(suffix for suffix, _ in CARD_FRAME_SIZE_SHARES)
    for name in sorted(os.listdir(folder)):
        stem, extension = os.path.splitext(name)
        if extension.lower() != ".webp" or stem.endswith(suffixes):
            continue
        with Image.open(os.path.join(folder, name)) as source:
            source = source.convert("RGBA")
            for suffix, share in CARD_FRAME_SIZE_SHARES:
                width = max(1, round(source.size[0] * share))
                height = max(1, round(source.size[1] * share))
                source.resize((width, height), Image.LANCZOS).save(
                    os.path.join(folder, stem + suffix + ".webp"), "WEBP", quality=WEBP_QUALITY, method=6)
                print("  ", "cards/frames/" + stem + suffix, "%dx%d" % (width, height))


def main():
    global FORCE
    FORCE = "--force" in sys.argv
    print("Generating Honeycomb placeholder art into:", ART)
    if FORCE:
        print("  --force: EVERY generated path will be overwritten, real art included")
    # `--only ui` rebuilds just the UI frames, leaving every other asset as it is.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["ui"]:
        build_ui_frames()
        print("Done.")
        return
    # `--only broken` rebuilds just the two derived cut-in masks, touching nothing else. Safe to run
    # against a folder full of real art.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["broken"]:
        build_broken_masks()
        build_broken_portraits()
        build_recover_portraits()
        print("Done.")
        return
    # `--only lewd` rebuilds just the Lewd supertype's frames and icon.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["lewd"]:
        build_lewd_card_type()
        build_card_frame_sizes()
        print("Done.")
        return
    # `--only frames` writes the downsampled copy of every card frame for each card size (session 15).
    # Run it after adding or redrawing any frame in cards/frames. Touches nothing else.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["frames"]:
        build_card_frame_sizes()
        print("Done.")
        return
    # `--only enemies` rebuilds every enemy's pose set and the enemy cut-in stand-ins (session 11: the new
    # enemy drawings), and nothing else.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["sidecars"]:
        build_art_owed_sidecars()
        print("Done.")
        return
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["enemies"]:
        build_enemies()
        build_broken_portraits()
        print("Done.")
        return
    # `--only maps` rebuilds just the hand-placed map backdrops (session 17: the floors doubled and the
    # paintings became panoramas). Touches nothing else.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["maps"]:
        build_map_backdrops()
        print("Done.")
        return
    # `--only poses` (2026-09-22) is the one to run after character art lands. It CLEARS the character
    # stand-ins first -- `--only characters` does not, and it rewrites each manifest with only what it
    # just made, so a stand-in it no longer writes (the old hurt tier, the old exposed) would fall off the
    # manifest and pass for a drawing forever after. Then it writes each outfit's stand-ins and the
    # Infernal attack tilts. It never touches card art, maps, UI, or any other enemy.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["poses"]:
        if FORCE:
            sys.exit("--only poses refuses --force: it would clear every character folder, drawings included")
        clear_previous_output(["characters"])
        build_characters()
        build_enemies(flagged_only=True)
        print("Done.")
        return
    # `--only characters` rebuilds every character's outfits and cut-in stand-ins plus the card art, and
    # nothing else (session 8: new outfits and cards without regenerating every background).
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["characters"]:
        build_characters()
        build_card_art()
        build_broken_portraits()
        build_recover_portraits()
        build_exposed_text()
        print("Done.")
        return
    # `--only exposed` rebuilds just the Exposed cut-in's title art. The per-outfit exposed sprites are
    # part of each character's pose set and come from `--only characters`.
    if "--only" in sys.argv and sys.argv[sys.argv.index("--only") + 1:][:1] == ["exposed"]:
        build_exposed_text()
        print("Done.")
        return
    print("Sources:")
    stash_sources()
    clear_previous_output()
    build_characters()
    build_enemies()
    build_art_owed_sidecars()
    build_card_art()
    build_backgrounds()
    build_map_backdrops()
    build_ui_frames()
    build_broken_masks()
    build_broken_portraits()
    build_recover_portraits()
    build_exposed_text()
    build_lewd_card_type()
    build_card_frame_sizes()
    print("Done.")


if __name__ == "__main__":
    main()
