var bodyKeywordDB = {
	// Brand keywords live in brandsDB2.js, not here — including the ones that
	// are not characters, which is what its "generic terms" section is for.
	//
	// They cannot live here anyway: a keyword DB string runs through
	// expandPlaceholders, where "(token)" is EXPANSION SYNTAX and these six
	// tokens are reserved —
	//     color, variant, size, ornament, shape, species
	// — so "pal (species)" was read as "pal, once per species" and quietly
	// became 46 entries: pal avian, pal bird, pal dog, pal corgi... The literal
	// tag was never registered. An unreserved token like "(doa)" survives as-is
	// with a console.warn, so the trap only springs on those six words.
	"bodyBrand": {
		"series": [
			"biker rosalina",
			"cosmic rosalina",
			"tekken 8",
			"sheikah symbol",
		],
	},
	"bodyRace": {
		"species": [
			"chibi",
			"(species)",
			"(species) girl",
			"(species) boy",
			"catgirl",
			"catboy",
			"doggirl",
			"dogboy", 
			"loli",
			"shota",
			"cute boy",
			"cute girl",
			"very cute",
			"child",
            "young",
            "cub",
			"imp",
			"twili",
			"gnome",
			"jiangshi",
			"arthropod",
			"arthropod girl",
			"monster girl",
			"harpy",
			"lamia",
			"mummy",

			"raptor",
			"velociraptor",
			"dinosaur",

			"dryad",
			"plant girl",
			"flora fauna",
			"cactus girl",

			"robot",
			"robot girl",
			"robot joints",
			"doll",
			"doll joints",
			"android",
			"mecha",
			"mecha musume",
			"asian",
			"asian female",
			"banshee",
			"bumble bee",
			"charon",
			"clown girl",
			"coyote girl",
			"deity",
			"dinosaur girl",
			"dullahan",
			"elf",
			"faun",
			"ghost girl",
			"giant",
			"gilf",
			"hellhound",
			"jackal",
			"kobold",
			"living plushie",
			"manta ray",
			"mermaid",
			"minotaur",
			"ojou-sama",
			"oni",
			"princess",
			"satyr",
			"scylla",
			"spirit",
			"werewolf",
			"zombie girl",
			"bedsheet ghost",
			"leprechaun",
			"turkey",
			"panther",
			"plushie",
		],
		"body": [
			"toned",
			"athletic",
			"athletic female",
			"athletic male",
			"muscular",
			"muscular female",
			"muscular male",
			"tall",
			"taller female",
			"taller male",
			"short",
			"shorter female",
			"shorter male",
            "shortstack",
			"small",
			"smaller female",
			"smaller male",
			"micro",
			"micro female",
			"micro girl",
			"micro male",
			"old",
			"old woman",
			"older female",
			"old man",
			"older man",
            "milf",
            "dilf",
            "mature",
            "mature female",
            "mature male",
			"1girl",
            "loli",
			"1boy",
            "shota",
			"plump",
			"curvy",
			"petite",
			"skinny",
			"very skinny",
			"cute",
			"futanari",
			"girly",
			"femboy",
			"reverse trap",
			"tomboy",
			"goth",
			"genius",
			"male",
			"female",
           
            "freckles",
			"piercing",
			
			"ball with hyper features",
			"kyojiri loli",
			"kyojiri shota",
			"manly",
			"mechanical",
			"melting",
			"reflective body",
			"shiny body",
			"stitched body",
			"stuffed doll",
			"translucent",
			"translucent body",
			"translucent skin",
			"transparent",
			"transparent body",
			"transparent skin",
		],
		"skin": [
			"human",
			"not furry",
			"shiny skin",
			"dark skin",
			"light skin",
			"very dark skin",
			"very light skin",
			"wet",
			"tattoo",
			"tan",
			"tanlines",
			"bikini tan",
			"shorts tan",
			"reflective skin",
		],
        "veins": [],
		"wool": [],
		"fur": [
			"furry",
			"body fur",
			"furry female",
			"furry male",
			"anthro",
			"feral",
			"wet fur",
			"dappled fur",
			"spotted fur",
		],
		"countershading": [],
		"scales": [
			"scalie",
		],
		"fins": [],
		"feathers": [],
		"joints": [],
        "stitches": [],
		"stripes": [],
		"markings": [],
		"jewelry": [],
		"paws": [],
		"claws": [],
		"pawpads": [],
	},
	"bodyHead": {
		"halo": [
			"cracked halo",
			"colored halo",
			"symbol halo",
			"unusual halo",
		],
		"horns": [
			"horns through hat",
			"horns through helmet",
			"curved horns",
			"curled horns",
			"ram horns",
			"goat horns",
			"cow horns",
			"forehead horns",
			"tube horns",
			
			"spiral horns",
			"ribbed horns",
			
			"dragon horns",
			"oni horns",
			"demon horns",
			"2 horns",
			"4 horns",
			"3 horns",
			"extra horns",
			"dipstick horns",
			"single broken horn",
			"broken horn",
			"sharp horns",
			"(species) horns",
		],
		"horn rings": [],
		"antlers": [],
		"antenna": [],
		"antennae": [],
		"crest": [],
		"head crest": [],
		"head wings": [],
		"head fin": [],
		"head fins": [],
		"fin": [],
		"ear": [],
		"ears": [
			"ears through hat",
			"ears through helmet",
            "long pointy ears",
			
			"(species) ears",
			
			"ears up",
			"ears down",
			"lop ears",
			"pricked ears",
			"pointy ears",
			"round ears",
			"dipstick ears",
			"animal ears",
			"animal ear fluff",
			"(color) ear fluff",
			"(color) inner ears",
			"hair ears",
			"nub ears",
			"(color)-framed glasses",
			"hair behind ear",
			"ear covers",
		],
		"mushroom head": [
			"mushroom hat",
			"mushroom on head",
			"(color) mushroom hat",
		],
		"flower head": [
			
		],
		"head": [
			"(color) head",
			"sword through head",
		]
	},
	"bodyHair": {
		"hair": [
			"wavy hair",
			"curly hair",
			"flipped hair",
			"messy hair",
			"frizzy hair",
			"drill hair",
			"blunt hair",
			"swept hair",
			"straight hair",
            "asymmetrical hair",
			"sidelocks",
			"wolf cut",
			"flowing hair",
			
            "head tuft",
			"hair vents",
			"bald",
			"afro",
			"bob cut",
			"bowl cut",
			"buzz cut",
			"pixie cut",
			"undercut",
			"side cut",
			"side shave",
			"buzzcut",
			"hime cut",
			"crown braid",
			"braid",
			"single braid",
			"side braid",
			"double braid",
			"long braid",
			"braided hair",
			"fauxhawk",
			"fauxhawk haircut",

			"hair over shoulder",
			"hair off shoulder",
			"hair curtain",
			"hair curtains",

			"(shape) in hair",
			
			"mizura",
			"twintails",
			"braided twintails",
			"tri tails",
			"quad tails",
			"quin tails",
			"pigtails",
			"twin drills",
			"tri drills",
			"short twintails",
			"low twintails",
			"high twintails",
			"long twintails",
			
			"redundant",
			"one side up",
			"side up",
			"both sides up",
			"sides up",
			"2 sides up",
			"hair up",
			"half updo",
			"updo",
			"hair flaps",
			"hair vents",
			"hair intakes",
			"hair rings",

			"two side up",
			"floating hair",
			"crossed bangs",
			"french braid",
			"cone hair bun",
			"single side bun",
			"blunt ends",
			
			"hair bun",
			"low bun",
			"single hair bun",
			"single bun",
			"double bun",
			"hair buns",
			"heart hair bun",
			"bun with braided base",
			"braided bun",
			
			"hair streak",
			"colored hair streak",
			"streaked hair",
			"hair gradient",
			"colored hair gradient",
			"gradient hair",
			"colored inner hair",

			"tentacle hair",
			"head tentacle",
			"single head tentacle",
			"head tentacles",
			"2 head tentacles",
			"3 head tentacles",
			"4 head tentacles",
			"detached twintails",
			"split twintails",
			"detached ponytail",
			"double buns",
			"fluffy hair",
			"frilled hair tubes",
			"goo hair",
			"hair loop",
			"low-tied long hair",
			"sidecut",
			"split-color hair",
			"yarn hair",
			"two side up",
		],
        "hair gradient": [
            "colored hair gradient",
            "gradient hair",
        ],
		"highlights": [],
		"ponytail": [
			"braided ponytail",
			"low ponytail",
			"high ponytail",
			"short pontail",
			"long ponytail",
            "side ponytail",
			"ponytail over shoulder",
			"drill ponytail",
			"low-tied ponytail",
		],
		"hairtie": [
			"(color) hairties",
			"(color) ribbon hairtie",
			"(color) ribbon hairties",
		],
		"hairclip": [
			"(shape) hairclip",
		],
		"hairclips": [
			"(shape) hairclips",
			"multiple hairclips",
		],
		"hair ribbons": [],
		"hair scrunchie": [],
		"scrunchie": [],
		"hair baubble": [],
		"hair baubbles": [],
		"hair beads": [],
		"hair stick": [],
		"hair sticks": [],
		"hairstick": [],
		"hairpin": [],
		"comb": [],
		"hair comb": [
			"comb in hair",
		],
		"ahoge": [
			"heart ahoge",
			"antenna hair",
		],
		"hair ornament": [
			"snowflake hair ornament",
			"carrot hair ornament",
			"food-themed hair ornament",
		],
		"mane": [],
	},
	"bodyFace": {
		"face": [
			"faceless",
			"faceless female",
			"faceless male",
			"featureless face",
			"eyes visible through hair",
			"eye visible through hair",
			"beauty mark",
			"facial mark",
			"facial tattoo",
		],
		"forehead": [],
		"horn": [
			"horn through hat",
			"horn through helmet",
			"curved horn",
			"forehead horn",
			"single horn",
			"unicorn horn",
			"spiral horn",
			"ribbed horn",
			"dipstick horn",
			"sharp horn",
		],
		"horn ring": [],
		"bangs": [
			"blunt bangs",
			"whispy bangs",
			"swept bangs",
			"side bangs",
			"asymmetrical bangs",
			"diagonal bangs",
			"parted bangs",
			"braided bangs",
			"hair slicked back",
			"comb over",
			"bangs pinned back",
            "hair tuft",
			"side part",
			"center part",
			
			"hair over eyes",
			"hair over both eyes",
			"hair over eye",
			"hair over one eye",
		],
		"forelocks": [
			"braided forelocks",
		],
		"eyebrows": [
			"eyebrows visible through hair",
		],
		"eyebrow": [
			"eyebrow visible through hair",
		],
		"cheeks": [
            "cheek tuft",
            "cheek tufts",
        ],
		"cheek": [],
        "whiskers": [],
		"blush stickers": [],
		"cheek stickers": [],
		"teardrop tattoo": [],
	},
	"bodyOrbital": {
		"orbital": [
			"wrinkles",
			"eye wrinkles",
			"eye bags",
			"bags under eyes",
		],
		"eyeshadow": [],
		"orbital pattern": [],
		"eyeliner": [
			"mascara",
		],
		"eyelashes": [
        	"colored eyelashes",
		],
	},
	"bodyEyes": {
		"eyes": [
			"third eye",
			"spiral eyes",
			"spiral pupils",
			"swirly eyes",
			"extra eyes",
			"3 eyes",
			"4 eyes",
			"5 eyes",
			"6 eyes",
			"heterochromia",
			"eyeless female",
			"eyeless male",
			"solid eyes",
			"no pupils",
			"compound eyes",
			"blank eyes",
			"empty eyes",
			"blind",
			"mob eyes",
			"wide eyes",
			"wide-eyed",
			"half-closed eyes",
			"hair over eyes",
			"slanted eyes",
			"sanpaku",
			"button eyes",
			"droopy eyes",
			"slanted eyes",
			"sanpaku eyes",
			"solid oval eyes",
			"sparkling eyes",
			"always closed eyes",
			"symbol-shaped pupils",
		],
		"eye": [
			"one-eyed",
			"one eye",
			"single eye",
			"cyclops",
			"one eye obscured",
			"one eye covered",
			"hair over one eye",
		],
		"sclera": [
			"bloodshot eyes",
		],
		"pupils": [
			"vertical pupils",
			"horizontal pupils",
			"star pupils",
			"heart pupils",
			"spiral eyes",
			"ringed pupils",
			"ringed eyes",
			"hypnosis",
			"constricted pupils",
			"slit pupils",
			"bright pupils",
			"cephalopod eyes",
		],
	},
	"bodyMuzzle": {
		"muzzle": [],
		"snout": [],
		"nose": [
			"animal nose",
			"dot nose",
		],
		"lips": [],
		"fang": ["cute fang",],
		"fangs": ["vampire",],
		"mouth": [
			"stitched mouth",
			"lipstick",
			"flesh fang",
			"triangle mouth",
		],
		"trunk": [],
		"beak": [],
	},
	"bodyTeeth": {
		"teeth": [
			"sharp teeth",
			"upper teeth",
			"upper teeth only",
		],
		"tongue": [
			"split tongue",
			"forked tongue",
			"colored tongue",
		],
	},
	"bodyTorso": {
		"neck": [
			"snake hood",
			"cobra hood",
		],
		"throat": [],
		"neck fluff": [],
		"shoulders": [],
	},
	"bodyBack": {
		"dorsal fin": [],
	},
	"bodyWings": {
		"wings": [
			"(species) wings",
			"feathered wings",
			"back wings",
			"extra wings",
			"2 wings",
			"4 wings",
			"6 wings",
			"hagoromo",
		],
		"wing": [
			"single wing",
			"(species) wing",
			"feathered wing",
			"back wing",
		],
	},
	"bodyChest": {
		"chest": [

		],
		"collarbone": [
			"chest spike",
		],
		"cleavage": [],
		"navel": [],
		"stomach": [],
	},
	"bodyBreasts": {
		"breast": [
			
		],
		"breasts": [
			"flat chest",
			"pectorals",
			"backboob",
			"sideboob",
			"underboob",
			"breasts apart",
		],
	},
	"bodyAreolae": {
		"areola": [],
		"areolas": [],
	},
	"bodyNipples": {
		"nipple": [
			"inverted nipple",
		],
		"nipples": [
			"inverted nipples",
		],
		"ribs": [],
	},
	"bodyArms": {
		"shoulders": [],
		// Singular twin, added 2026-08-08. Every pattern reads the item name, so
		// only the plural existing meant `shoulder spikes` was uncategorised
		// while `shoulders spikes` — which nobody writes — was fine. Kept beside
		// the plural rather than replacing it, same call as the hyphen spellings.
		"shoulder": [],
		"arms": [
			"winged arms",
			"feathered arms",
			"bionic arms",
			"prosthetic arms",
			"armpits",
			"cannon arms",
			"skeletal arms",
		],
		"arm": [
			"amputee",
			"single arm",
			"bionic arm",
			"prosthetic arm",
			"armpit",
			"stump arm",
			"cannon arm",
			"skeletal arm",
		],
		"armpit hair": [],
		"armpit stubble": [],
		"biceps": [],
		"forearms": [],
		"wrists": [],
		"wrist fluff": [],
	},
	"bodyHands": {
		"hands": [
			"featureless hands",
			"2 fingers",
			"3 fingers",
			"4 fingers",
			"5 fingers",
			"clawed hands",
			"hooved hands",
			"animal hands",
		],
		"wrist fluff": [],
		"wrists": [],
	},
	"bodyFingernails": {
		"nails": [
			"sharp nails",
		],
		"fingers": [],
		"fingernails": [
			"sharp fingernails",
		],
	},
	"bodyBelly": {
		"navel": [
			"outie navel",
			"covered navel",
		],
		"belly button": [
			"outie belly button",
		],
		"pubic hair": [
			"pubic stubble",
			"excessive pubic hair",
			"pubic tuft",
		],
		"crotch": [],
		"crotch tuft": [],
	},
	"bodyWaist": {
		"belly": [
			"fat",
			"fat woman",
			"overweight",
			"overweight female",
			"overweight male",
			"chubby",
			"chubby female",
			"chubby male",
			"belly overhang",
			"pregnant",
			"abs",
			"ab line",
            "narrow waist",
			"thin waist",
			"hourglass figure",
			"bottom heavy",
			"bottom heavy female",
			"bottom heavy male",
		],
		"womb": [],
		"hips": [],
		"mermaid tail": [],
		"ghost tail": [],
	},
	"bodyPenis": {
		"penis": [
			"humanoid penis",
			"equine penis",
			"canine penis",
			"knotted equine penis",
			"cetacean penis",
			"tapering penis",
			"tapered penis",
			"porcine penis",
			"spiral penis",
			"ridged penis",
			"ribbed penis",
			"bumpy penis",
			"segmented penis",
			"resting penis",
			"sweaty penis",
			"micropenis",
			"small penis big balls",
			
			"(species) penis",
			
			"multiple penises",
			"extra penises",
			"diphalism",
			"vertical diphalism",
			"horizontal diphalism",
			"2 penises",
			"small but hung",
			"big balls small penis",
			"magic penis",
			"bow on penis",
			"extra penis",
			"ovipositor penis",
			"tentacle penis",
			"unsheathed penis",
			"genital sheath",
		],
		"ovipositor": [],
		"glans": [
			"foreskin",
			"long foreskin",
			"unretracted foreskin",
			"hyper foreskin",
		],
		"medial ring": [],
		"knot": [],
		"chastity cage": [
			"flat cage",
			"flat chastity cage",
		],
	},
	"bodyBalls": {
		"balls": [
			"futanari",
			"resting balls",
			"sweaty balls",
			"big balls small penis",
			"saggy balls",
			"very saggy balls",
			"low-hanging balls",
			"heavy balls",
		],
	},
	"bodyPussy": {
		"pussy": [
			"pussy peek",
			"(species) pussy",
			"peach pussy",
		],
		"labia": [
			"cleft of venus",
			"cervix",
		],
		"mons": [],
	},
	"bodyClit": {
		"clitoris": [
			"clitoral hood",
		],
	},
	"bodyButt": {
		"ass": [],
		"butt": [],
	},
	"bodyAnus": {
		"anus": [
			"(species) anus",
			"anus peek",
			"anus behind thong",
		],
	},
	"bodyTail": {
		"tail": [
			"dipstick tail",
            "fluffy tail",
            "scut tail",
            "scaly tail",
            "scalie tail",
			"skinny tail",
			"spade tail",
			"spiral tail",
			"curly tail",
			"tanuki tail",
			"(species) tail",
			"tuft tail",
			"round tail",
			"stub tail",
		],
		"tails": [
			"extra tails",
			"multiple tails",
			"2 tails",
			"3 tails",
			"4 tails",
			"6 tails",
			"8 tails",
			"9 tails",
		],
        "undertail": [],
		"tailfeathers": [],
		"abdomen": [],
	},
	"bodyLegs": {
		"legs": [
			"quadruped",
			"quadrupedal",
			"bipedal",
			"taur",
			"centaur",
			"spider-taur",
			"spider taur",
			"4 legs",
			"6 legs",
			"extra legs",
			"too many legs",
			"pointy knees",
			"tall",
			"bird legs",
			"orb lower body",
			"sphinx taur",
			"tall",
			"very tall",
		],
		"thighs": [
			"thigh gap",
		],
		// Singular twin, added 2026-08-08 — `thigh tattoo`, `thigh strap`.
		"thigh": [],
	},
	"bodyFeet": {
		"calves": [],
		"ankles": [],
		"ankle fluff": [],
		"feet": [
			"(species) feet",
			"barefoot",
			"clawed feet",
			"no toes",
			"2 toes",
			"3 toes",
			"4 toes",
			"5 toes",
			"hooved feet",
			"animal feet",
			"high-heeled feet",
		],
		"soles": [],
		"heels": [],
		"talons": [],
	},
	"bodyToenails": {
		"toes": [],
		"toenails": [],
		"pawpads": [],
		"hooves": [
			"cloven hooves",
		],
	},
	"bodyUnsorted": {

	},
}