var clothesKeywordDB = {
	"clothesFullwear": {
        "clothing": [
			"skimpy",
			"skimpy clothes",
			"skimpy clothing",
			"skimpy outfit",
			"revealing clothes",
			"revealing clothing",
			"revealing outfit",
			"pointless clothes",
			"pointless clothing",
			"pointless outfit",
			"useless clothes",
			"useless clothing",
			"useless outfit",
			"lewd clothes",
			"lewd clothing",
			"lewd outfit",
			"precarious clothes",
			"precarious clothing",
			"precarious outfit",
			"barely clothed",
			"mostly nude",
			"functionally nude",
            "fully clothed",
			"fully zipped",
			"diagonal stripes",
			"horizontal stripes",
			"vertical stripes",
			"chinese clothes",
			"chinese clothing",
			"japanese clothes",
			"japanese clothing",
			"egyptian",
			"egyptian clothes",
			"egyptian clothing",
            "indian",
            "indian clothes",
			"indian clothing",
			"greek",
			"greek clothes",
			"greek clothing",
			"gym clothes",
			"sleeveless",
			"strapless",
			"cross",
			"ribbon",
			"nude",
			"tassels",
			"dirty clothes",
			"barbarian",
			"butler",
			"detective",
			"samurai",
			"torn robes",
			"robe",
			"robes",
			"pouches",
			"big zipper",
			"oversized zipper",
			"zipped",
			"black knight",
			"unusual miko",
			"unusual shrine maiden",
			"eden academy uniform",
			"exposed",
			"mad scientist",
			"superheroine",
			"sailor uniform",
			"necromancer",
			"cleric",
			"bancho",
			"body paint",
			"chainmail",
			"sackcloth",
			"sideless outfit",
			"clockwork",
			"automaton",
			"battle damage",
			"crotch tear",
        ],
		"clothes": [
			"clothes writing",
			"fancy clothes",
			"(color) ribbon back ornament",
			"(color) tassels",
			"(color) ribbon chest ornament",
			"(color) rose chest ornament",
			"vertical-striped clothes",
		],
		"outfit": [
			"harem outfit",
			"harem silks",
			"miko",
			"nontraditional miko",
			"shrine maiden",
			"military uniform",
			"santa outfit",
			"sheet ghost",
			"ghost costume",
			"formal",
			"professional",
			"gym outfit",
			"gym uniform",
			"nun",
			"schoolboy",
			"schoolgirl",
			"school uniform",
			"maid",
			"maid outfit",
			"maid uniform",
			"ninja",
			"ninja outfit",
			"nurse",
			"nurse outfit",
			"nurse uniform",
			"baseball",
			"baseball uniform",
			"cheerleader",
			"cheerleader uniform",
			"waitress",
			"waitress uniform",
			"barmaid",
			"barmaid uniform",
            "police",
            "police uniform",
			"spacesuit",
			"mechanic",
			"chinese clothes",
			"japanese clothes",
			"egyptian",
			"ancient egyptian",
			"egyptian clothes",
			"magical girl",
			"lingerie",
			"playboy bunny",
			"bunnygirl",
			"reverse bunnysuit",
			"reverse outfit",
			"meme outfit",
			"bandages",
			"torn bandages",
			"space pirate",
            "gothic",
			"gothic lolita",
			"punk",
            "tribal",
            "tribal clothes",
            "tribal outfit",
            "indian outfit",
            "indian fashion",
            "roswaal mansion maid uniform",
			"cosplay",
			"cheerleader outfit",
			"hero outfit",
			"cowboy",
			"fortune teller",
			"superhero costume",
			"tokusatsu",
			"gakuran",
			"race queen",
			"idol",
			"office lady",
			"power armor",
			"shoulder armor",
			"uniform",
			"haori",
			"dougi",
			"pilot suit",
		],
		"armor": [
			"full armor",
			"knight",
			"soldier",
			"space marine",
		],
		"buttons": [
			"buttoned",
			"partially buttoned",
			"fully buttoned",
			"unbuttoned",
			"partially unbuttoned",
			"fully unbuttoned",
		],
		"bodystocking": [
			"bodystocking under clothes",
		],
		"bikini": [
			"bikini armor",
			"micro bikini",
			"venus bikini",
			"string bikini",
			"leaf bikini",
			"eyepatch bikini",
			"chainmail bikini",
			"bikini under clothes",
			"golden bikini",
			"cow-print bikini",
			"side-tie bikini",
		],
		"scrubs": [],
		"suit": [
			"tuxedo",
			"pinstripe suit",
			"business suit",
			"pant suit",
			"track suit",
		],
		"bodysuit": [
			"unitard",
			"jumpsuit",
			"bikesuit",
			"skinsuit",
			"bodysuit under clothes",
		],
		"cutout": [],
		"dress": [
			"front-laced dress",
			"halterneck dress",
			"china dress",
			"coat dress",
			"cocktail dress",
			"denim dress",
			"pencil dress",
			"pinafore dress",
			"sailor dress",
			"santa dress",
			"sweater dress",
			"tennis dress",
			"trapeze dress",
			"tube dress",
			"wedding dress",
			"armored dress",
			"backless dress",
			"collared dress",
			"frilled dress",
			"fur-trimmed dress",
			"half-dress",
			"halter dress",
			"highleg dress",
			"hobble dress",
			"latex dress",
			"layered dress",
			"long dress",
			"off-shoulder dress",
			"pleated dress",
			"ribbed dress",
			"short dress",
			"slit dress",
			"sundress",
			"tube dress",
			"sleeveless dress",
			"strapless dress",
			"very long dress",
			"cake dress",
			"dirndl",
			"flowing dress",
			"funeral dress",
			"mermaid dress",
			"ball gown",
			"sideless dress",
			"high-low dress",
			"fluffy dress",
			"medium dress",
			"very short dress",
		],
		"underdress": [],
		"leotard": [
			"bunnysuit",
			"leotard under clothes",
			"leotard over clothes",
		],
		"pajamas": [],
		"robe": [],
		"ribbon": [],
		"swimsuit": [
			"slingshot swimsuit",
			"one-piece swimsuit",
			"one piece swimsuit",
			"swimsuit under clothes",
		],
		"serafuku": [],
		"sheet": [],
		"towel": [
			"towel over clothes",
			"towel around chest",
			"towel around neck",
			"towel around waist",
		],
		"rose": [],
		"print": [
			"cross print",
			"skull print",
			"logo print",
			"print logo",
			"text print",
			"print text",
		],
		"trim": [

		],
		"underwear": [],
	},
	"clothesHeadwear": {
		"balaclava": [],
		"crown": [],
		"bandanna": [],
		"hairband": [
			"fake animal ears",
			"fake horns",
			"fake antlers",
		],
		"habit": [],
		"headgear": [],
		"hat": [
			"santa hat",
			"baseball cap",
			"beret",
			"bicorne",
			"tricorne",
			"bowler hat",
			"bucket hat",
			"cavalier hat",
			"cowbow hat",
			"straw hat",
			"fedora",
			"female service cap",
			"flat cap",
			"flat hat",
			"mob cap",
			"pirate hat",
			"sombrero",
			"sun hat",
			"sunhat",
			"top hat",
			"witch hat",
			"pointy hat",
			"wizard hat",
			"deerstalker",
			"chef hat",
			"beanie",
			"(color) beanie",
			"fez hat",
			"mitre",
			"nightcap",
			"nurse hat",
			"nurse cap",
			"jester hat",
			"jester cap",
			"visor cap",
			"(color) visor cap",
			"peaked cap",
			"mini hat",
			"mini top hat",
			"hat through ears",
			"mouth hat",
            "flower hat",
			"qipao",
			"conductor hat",
			"flower crown",
			"hair over hairband",
			"backwards cap",
			"animal ear hat",
			"cowboy hat",
			"goggles on hat",
			"pumpkin hat ornament",
		],
		"hat band": [],
		"hat wrap": [],
		"cap": [],
		"brim": [],
		"visor": [],
		"veil": [
			"head veil",
			"wedding veil",
			"bridal veil",
			"(color) head veil",
		],
		"head scarf": [],
		"headdress": [
			"maid headdress",
		],
		"helmet": [
			"pith helmet",
			"space helmet",
			"winged helmet",
			"knight helmet",
			"kettle helmet",
			"bucket helmet",
			"spiked helmet",
			"mini crown",
			"flaming helmet",
			"knight visor",
			"visor up",
		],
		"hijab": [],
		"hood": [
			"animal hood",
			"cat-eared hood",
			"bunny hood",
			"ears through hood",
			"hood up",
			"hood down",
			"hair through hood",
		],
        "bow": [],
		"tiara": [],
		"panties on head": [],
	},
	"clothesForeheadwear": {
		"circlet": [],
		"veil": [
			"eye veil",
		],
		"headband": [],
		"forehead protector": [],
		"half mask": [],
		"sweatband": []
	},
	"clothesFacewear": {
		"mask": [
			"face mask",
			"full mask",
			"tribal mask",
			"plague doctor mask",
			"plague mask",
		],
		"face visor": [],
		"veil": [
			"face veil",
			"eyes visible through veil",
			"mouth visible through veil",
			"face visible through veil",
			"(color) face veil",
		],
		"talisman": [
			"ofuda on head",
			"ofuda on hat",
		],
	},
	"clothesEyewear": {
		"blindfold": [
			"blindfold up",
			"blindfold askew",
			"blindfold over one eye",
		],
		"eye mask": [],
		"eye visor": [],
		"eyepatch": [],
		"glasses": [
			"round glasses",
			"square glasses",
			"circle glasses",
			"rectangular",
			"thick-rimmed glasses",
			"thick-framed glasses",
			"(shape) glasses",
			"rimless glasses",
			"semi-circular glasses",
			"over-rim glasses",
			"under-rim glasses",
			"(color)-tinted glasses",
		],
		"goggles": [
			"(color)-tinted goggles",
		],
		"monocle": [],
		"pince-nez": [],
		"sunglasses": []
	},
	"clothesMouthwear": {
		"mouth veil": [],
		"mouth mask": [
			"surgical mask",
			"covid mask",
		],
		"gasmask": [],
		"pacifier": []
	},
	"clothesEarwear": {
		"earring": [
			"(shape) earring",
			"pearl earring",
			"earpiece",
		],
		"earrings": [
			"(shape) earrings",
			"pearl earrings",
			"ear piercings",
			"ear piercing",
			"stud piercings",
			"stud piercing",
			"multiple earrings",
			"(color) ear piercings",
		],
		"ear clip": [
			"clip piercing",
			"clip piercings",
		],
		"headphones": [],
		"earmuffs": []
	},
	"clothesNeckwear": {
		"amulet": [],
		"ascot": [],
		"bowtie": [],
		"choker": [
			"(shape) choker"
		],
		"collar": [
			"detached collar",
			"sailor collar",
			"animal collar",
			"high collar",
			"flaired collar",
            "popped collar",
			"usekh collar",
			"(shape) collar",
			"winged collar",
			"wing collar",
			"clerical collar",
			"flared collar",
			"(color) high collar",
			"(color) flower necklace",
			"stitched high collar",
		],
		"fur collar": [
			"fluffy collar",
		],
		"lei": [],
		"locket": [],
		"magatama": [],
		"neck bell": [],
		"neck ribbon": [],
		"neck ring": [],
		"gem neck ornament": [],
		"neckerchief": [
			"american flag neckerchief",
		],
		"necklace": [
			"chain necklace",
			"(shape) necklace",
            "pearl necklace",
			"(shape) brooch",
			"(color) brooch",
		],
		"necktie": [
			"necktie between breasts",
		],
		"sailor collar": [],
		"stethoscope": [],
		"tie": [
			"tie between breasts",
			"bolo tie",
		],
		"pendant": [],
		"prayer beads": [],
		"scarf": [],
		"stole": [],
		"shawl": []
	},
	"clothesShoulderwear": {
		"cape": [
			"coat on shoulders",
			"shoulder coat",
			"jack on shoulders",
		],
		"capelet": [
			"side capelet",
		],
		"cloak": [],
		"mantle": [],
		"epaulettes": [],
		"pauldron": [
			"huge pauldron",
			"single pauldron",
		],
		"pauldrons": [
			"huge pauldrons",
		],
		"poncho": [],
		"shoulderpad": [
			"single shoulderpad",
			"wooden shoulderpad",
		],
		"shoulderpads": [],
		"side cape": [],
		"shoulder cape": [],
	},
	"clothesArmwear": {
		"armband": [
            "bicep bracelet",
            "bicep band",
            "arm garter",
        ],
		"armbands": [],
		"arm belts": [],
		"arm belt": [],
		"arm straps": [],
		"arm strap": [],
		"arm ribbons": [],
		"arm ribbon": [],
		"arm rings": [],
		"arm ring": [],
		"armlets": [],
		"armlet": [],
		"sleeve cuffs": [],
		"sleeve cuff": [],
		"sleeves": [
            "detached sleeves",
            "dagged sleeves",
			"puffy short sleeves",
			"juliet sleeves",
			"medium sleeves",
			"feathered sleeves",
			"juliette sleeves",
			"miko sleeves",
			"sleeves past wrist",
			"puffy long sleeves",
        ],
		"sleeve": [
			"single sleeve",
			"asymetrical sleeves",
			"asymetrical armwear",
		],
		"elbow gloves": [],
		"elbow glove": [
			"single elbow glove",
			"asymetrical elbow gloves",
			"asymetrical gloves",
		],
		"puffy sleeves": [],
	},
	"clothesWristwear": {
		"armguard": [],
		"armguards": [],
		"bangle": [],
		"bangles": [],
		"bracelet": [
			"spiked bracelet",
		],
		"bracelets": [
			"spiked bracelets",
		],
		"bracer": [],
		"bracers": [],
		"cuff": [
			"single cuff",
			"detached cuff",
			"wrist cuff",
		],
		"cuffs": [
            "detached cuffs",
            "corsage",
			"wrist cuffs",
			"handcuffs",
        ],
		"cufflinks": [],
		"shackle": [],
		"shackles": [
			"wrist shackles",
		],
		"wristguard": [],
		"wristguards": [],
		"wristband": [],
		"wristbands": [],
		"wristwatch": [],
		"forearm wrap": [],
		"forearm wraps": [],
		"wrist wrap": [],
		"wrist wraps": [],
		"wrist scrunchie": [],
		"vanbrace": [],
		"vanbraces": [],
	},
	"clothesHandwear": {
		"glove": [
			"single glove",
		],
		"gloves": [
			"half gloves",
			"boxing gloves",
			"fingerless gloves",
			"bridal gauntlets",
			"animal hands",
			"paw gloves",
			"clawed gloves",
		],
		"gauntlet": [
			"single gauntlet",
			"clawed gauntlets",
		],
		"halfgloves": [],
		"gauntlets": [],
		"mittens": [],
		"oven mits": [],
		"ring": [],
		"rings": [],
        "pom-poms": [],
	},
	"clothesUpperwearOuter": {
		"blazer": [],
        "breastplate": [
            "(shape) breastplate",
        ],
		"cardigan": [],
		"chest wraps": [],
		"coat": [
			"raincoat",
			"trench coat",
			"winter coat",
			"duffel coat",
			"fur coat",
			"overcoat",
			"peacoat",
			"labcoat",
            "double buttoned",
            "double breasted",
            "single buttoned",
			"lab coat",
		],
		"gown": [],
		"hoodie": [],
		"jacket": [
			"letterman jacket",
			"safari jacket",
			"suit jacket",
			"bomber jacket",
			"flame-print jacket",
			"high-collar jacket",
			"kimono jacket",
			"split-color jacket",
			"tartan jacket",
			"unzipped jacket",
		],
		"kimono": [],
		"nightgown": [
			"negligee",
		],
		"sweater": [
			"turtleneck sweater",
			"ribbed sweater"
        ],
        "bandolier": [],
        "backpack": [
            "randerosu",
			"randoseru",
        ],
        "jetpack": [],
	},
	"clothesUpperwearMiddle": {
		"apron": [
            "maid apron",
        ],
		"breast curtains": [],
		"breast curtain": [
			"long breast curtain",
		],
		"harness": [
			"o-ring harness",
		],
		"straps": [],
		"overalls": [
			"overall shorts",
			"overall skirt",
			"overall dress",
		],
		"suspenders": [],
		"tabard": [],
		"vest": [
            "sweater vest",
			"patch vest",
        ],
        "placard": [],
	},
	"clothesUpperwearInner": {
		"bandeau": [
			"belt bra",
			"(color) belt bra",
		],
		"shirt": [
			"t-shirt",
			"tank top",
			"collared shirt",
			"dress shirt",
			"compression shirt",
			"criss-cross halterneck",
			"halterneck",
			"chinese shirt",
			"chestless shirt",
			"partially unbuttoned shirt",
			"floral-print shirt",
			"polka-dot shirt",
			"turtleneck shirt",
			"undersized shirt",
		],
		"blouse": [],
		"bodice": [],
		"chest wrap": [],
		"aloha shirt": [],
		"placcard": [
			"stitched placcard",
		],
		"toga": [],
		"tube top": [],
		"sling top": [],
		"tunic": []
	},
	"clothesUpperwearUnder": {
		"bra": [
			"sports bra",
			"lace bra",
			"feather bra",
			"feathered bra",
			"cow-print bra",
		],
		"sarashi": [],
		"pasties": [
			"heart pasties",
			"skull pasties",
			"star pasties",
			"cross pasties",
			"tape pasties",
			"x pasties",
			"flaming pasties",
		]
	},
	"clothesUpperwear": {
		"upperwear": [
			"uppershirt only",
			"(color) uppershirt",
		],
		"topwear": [],
		"top": [
			"halter top",
			"sling bikini top",
			"breast window",
			"center frills",
		],
	},
	"clothesNipplewear": {
		"nipple barbells": [],
		"nipple chain": [],
		"nipple rings": [],
		"nipple plug": [],
		"nipple plugs": [],
		"nipple piercing": [
			"safety pin piercing",
			"id card piercing",
			"name tag nipple piercing",
			"nipple tassles",
		],
	},
	"clothesWaistwear": {
		"belt": [
			"extra belts",
			"belts askew",
			"(color) bow waist ornament",
			"belt askew",
			"double belt",
			"chain belt",
			"(color) bead belt",
		],
		"buckle": [],
		"belt buckle": [],
		"belt pouch": [],
		"coattails": [],
		"pouch": [],
		"corset": [
			"corset over navel",
			"(color) underbust corset",
			"(color) underbust corset",
			"(color) overbust corset",
		],
		"sash": [],
		"waistband": [],
		"waistcoat": [],
		"waist chain": [],
	},
	"clothesLowerwearOuter": {
		"loincloth": [
			"loincloth cutout",
		],
		"skirt": [
			"pleated skirt",
			"pencil skirt",
			"high-low skirt",
			"overall skirt",
			"suspender skirt",
			"microskirt",
			"micro skirt",
			"miniskirt",
			"kimono skirt",
			"slit skirt",
			"high-low skirt",
			"detached skirt",
			"high-waisted skirt",
			"long-sleeved skirt",
			"lowleg skirt",
			"medium skirt",
			"miko skirt",
			"petal skirt",
			"showgirl skirt",
			"hakama skirt",
		],
		"sarong": [
			"side-tie sarong",
		],
		"underskirt": [],
	},
	"clothesLowerwearInner": {
		"pants": [
			"yoga pants",
			"jeans",
			"leather pants",
			"sweatpants",
			"assless pants",
			"crotchless pants",
			"chaps",
			"detached pants",
			"flaired pants",
			"bellbottoms",
			"slacks",
			"rolled-up pants",
			"cargo pants",
			"pants under skirt",
			"medium pants",
			"harem pants",
			"pants rolled up",
			"assless chaps",
			"single pantsleg",
		],
		"shorts": [
			"bike shorts",
			"spats",
			"denim shorts",
			"dolphin shorts",
			"gym shorts",
			"booty shorts",
			"microshorts",
			"micro shorts",
			"minishorts",
			"jean shorts",
			"shorts under skirt",
			"bodysuit shorts",
			"flame-print shorts",
			"high-waist shorts",
		],
		"bloomers": [],
		"hakama": [],
		"pantyhose": [],
		"tights": [
			"bat-print tights",
		],
		"leggings": [],
	},
	"clothesLowerwearUnder": {
		"panties": [
            "panty",
			"string panties",
			"bow panties",
			"panty bow",
			"shimapan",
        ],
		"thong": [],
		"c-string": [],
		"g-string": [],
		"maebari": [
			"(shape) maebari"
		],
		"speedo": [],
        "cock ring": [],
        "ball bra": [],
        "ball ring": [],
        "ball stretcher": [],
		"bikini bottom": [
			"(color) bikini bottoms",
			"side-tie bikini bottom",
		],
	},
	"clothesLowerwear": {
		"lowerwear": [
			"hip vents",
		],
	},
	"clothesLegwearUpper": {
		"thighhigh": [
			"stirrup thighhigh",
			"toeless thighhigh",
			"zettai ryouiki",
			"zettai ryouki",
			"thighhigh under boot",
			"thighhigh under thighboot",
		],
		"thighhighs": [
			"stirrup thighhighs",
			"toeless thighhighs",
			"zettai ryouiki",
			"thighhighs under boots",
			"thighhighs under thighboots",
		],
		"fishnet thighhigh": [],
		"fishnet thighhighs": [
			"fishnets",
		],
		"kneesock": [],
		"kneesocks": [],
		"kneehigh": [],
		"kneehighs": [],
		"kneepad": [],
		"kneepads": [],
		"thigh strap": [],
		"thigh straps": [],
		"thighband": [],
		"thighbands": [],
		"thighbelt": [],
		"thighbelts": [],
		"leg belt": [],
		"leg belts": [],
		"garter straps": []
	},
	"clothesLegwearLower": {
		"sock": [
			"knee high",
			"stirrup sock",
			"toeless sock",
		],
		"socks": [
			"tabi",
			"knee highs",
			"stirrup socks",
			"toeless socks",
			"stirrup legwear",
			"toeless legwear",
			"rolled-up socks",
		],
		"anklet": [
			"spiked anklet",
		],
        "anklets": [
			"spiked anklets",
		],
		"knee pad": [],
		"knee pads": [],
        "ankle ring": [],
        "ankle rings": [],
		"shinguard": [],
		"shinguards": [],
		"legwarmer": [],
		"legwarmers": []
	},
	"clothesFootwear": {
		"shoe": [
			"high heel",
			"lace-up shoe",
			"front-laced shoe",
			"platform shoe",
			"loafer",
			"sneaker",
			"animal shoe",
			"paw shoe",
		],
		"shoes": [
			"high heels",
			"lace-up shoes",
			"front-laced shoes",
			"platform shoes",
			"mary janes",
			"loafers",
			"sneakers",
			"flats",
			"animal shoes",
			"paw shoes",
			"crocs",
			"(color) crocs",
			"open-toed shoes",
		],
		"boot": [
			"platform boot",
			"lace-up boot",
			"front-laced boot",
			"high-heeled boot",
            "cowboy boot",
			"combat boot",
			"dress shoe",
			"pointy shoe",
			"knee boot",
			"single boot",
		],
		"boots": [
			"platform boots",
			"lace-up boots",
			"front-laced boots",
			"high-heeled boots",
            "cowboy boots",
			"combat boots",
			"dress shoes",
			"pointy shoes",
			"knee boots",
			"huge boots",
			"kneehigh boots",
			"zipped boots",
			"clawed boots",
		],
		"thighboots": [
			"platform thighboots",
			"lace-up thighboots",
			"front-laced thighboots",
			"high-heeled thighboots",
			"diagonal thighboots",
		],
		"greaves": [
			"clawed greaves",
		],
		"sandals": [
			"wooden sandals",
		],
		"slippers": [
			"ballet slippers",
			"fuzzy slippers",
			"bunny slippers",
		],
		"laces": [],
	},
	"clothesUnsorted": {
	},
	"weapons": {
		"cane": [],
		"rapier": [],
		"lance": [],
		"playing card": [
			"tarot card",
		],
		"staff": [
            "wooden staff",
            "cane staff",
        ],
		"axe": [
            "greataxe",
            "double axe",
            "handaxe",
        ],
		"mace": [
			"flanged mace",
		],
		"cleaver": [],
		"sickle": [],
		"scepter": [
			"sceptre",
		],
		"sword": [
            "greatsword",
            "longsword",
            "shortsword",
            "broadsword",
            "katana",
        ],
        "shield": [
            "greatshield",
            "buckler",
        ],
		"knife": [
            "dagger",
        ],
		"beam saber": [],
		"lightsaber": [],
		"gun": [
            "pistol",
            "handgun",
            "revolver",
			"energy gun",
			"ray gun",
        ],
		"rifle": [],
		"shotgun": [],
		"polearm": [],
		"spear": [],
		"rocket launcher": [],
		"weapon": [],
	}
}