var modifierKeywordDB = {
	"colors": [
		"white",
		"grey",
		"black",
		"maroon",
		"pink",
		"red",
		"orange",
		"brown",
		"tan",
		"beige",
		"yellow",
		"lime",
		"green",
		"teal",
		"aqua",
		"blue",
		"periwinkle",
		"purple",
		"violet",
		"rainbow",
		"gold",
		"silver",
		"bronze",
		"copper",
		"metal",
		"steel",
		"plant",
		"leaf",
		"stone",
        "skin",
        "starry",
        "cosmic",
        "tribal",
        "plaid",
        "latex",
        "pale",
		"neon",
		"glowing",
		"monotone",
		// Added 2026-08-08. Materials and finishes already sit in this list —
		// `latex`, `metal`, `plaid` — so these belong with them:
		// camouflage hoodie, denim jacket, shiny shorts.
		// NOTE the spelling: unsorted.md said `camoflague`, but the tag in
		// charactersDB is `camouflage hoodie` and that is the one that matters.
		"flaming",
		"camouflage",
		"denim",
		"shiny",
		// `blonde streak` and `blonde streaks` were asked for as bare lines
		// rather than under Missing colors, so this one is inferred. It also
		// gives `blonde <anything>` — drop it if that is not wanted.
		"blonde",
	],
	"variants": [
		"light",
		"dark",
	],
	"sizes": [
		"wide",
		"oversized",
		"small",
		"big",
		"short",
		"long",
        "puffy",
	],
	"ornaments": [
		"bell",
		"bow",
		"butterfly",
		"crescent",
		"cross",
		"cowbell",
		"feather",
		"flower",
		"food-themed",
		"gem",
		"heart",
		"hoop",
		"jewel",
		"moon",
		"pom pom",
		"ribbon",
		"rose",
		"skull",
		"star",
		"stud",
		"wing",
		// Added 2026-08-08, for `{item} {ornament}` and `{color} {item} {ornament}`:
		// gold neck rings, hair feathers, hair flowers, arm shackle, red hair tubes.
		// Plurals sit beside their singulars on purpose — `feather` and `feathers`
		// are different tags and the training data has both.
		"rings",
		"feathers",
		"flowers",
		"shackle",
		"tubes",
		// The new `{ornament} {item}` and `{ornament} {item} ornament(s)` rows
		// read this list, so these four are what makes them reach the tags that
		// asked for them: ball earrings, shell earrings, fish hair ornament,
		// white scrunchie hair ornaments. `fish` is also a species — different
		// slot, no conflict.
		"ball",
		"shell",
		"fish",
		"scrunchie",
	],
	"shapes": [
		"butterfly",
		"crescent",
		"cross",
		"feather",
		"flower",
		"gem",
		"heart",
		"hoop",
        "jewel",
		"moon",
		"rose",
		"skull",
		"star",
		"stud",
		// Added 2026-08-08 — `{shape} {symbol}` then covers `flame tattoo`.
		"flame",
	],
    "modifiersSleeves": [
        "long-sleeved",
        "medium-sleeved",
        "short-sleeved",
        "sleeveless",
        "puffy-sleeved",
    ],
    "modifiersLowerwear": [
        "highleg",
        "lowleg",
        "side-tie",
        "crotchless",
		"high-waisted",
		"high waisted",
		"low-waisted",
		"low waisted",
    ],
    "modifiersFootwear": [
        "high-heeled",
        "platform",
        "toeless",
        "stirrup"
    ],
    "modifiersGlobal": [
        "armored",
        "baggy",
		"belted",
        "broken",
        "buttoned",
		"cactus",
        "checkered",
        "cropped",
        "dagged",
		"diagonal-striped",
        "frilled",
        "frilly",
		"front-laced",
		"front-tied",
        "fur",
        "fur-trim",
		"fuzzy",
        "glowing",
        "gradient",
        "hooded",
        "lace",
        "lace-trim",
		"laced",
		"laced-up",
		"lacey",
        "layered",
        "leather",
        "loose",
		"military",
		"mechanical",
		"multicolored",
        "naked",
        "no",
		"off-shoulder",
        "open",
		"oversized",
        "print",
		"pinstripe",
        "ragged",
		"ripped",
		"ribbed",
        "ruffled",
        "see-through",
        "sheer",
        "strapless",
        "striped",
        "spiked",
        "single",
        "skin tight",
		"tied",
        "tight",
        "torn",
        "transparent",
        "unbuttoned",
        "untied",
        "winged",
        "winter",
		"zig-zagged",
		"zigzag",
		"clawed",
    ],
    "actionPrefixes": [
        "grabbing",
        "hands on",
        "lifting",
        "pulling",
        "tugging on"
    ],
    "actionSuffixes": [
        "down",
        "grab",
        "lift",
        "pull",
        "tug",
        "aside",
    ],
    "symbols": [
        "tattoo",
        "marking",
        "pattern",
        "symbol",
        "scar",
        "bruise",
		"mole",
		// Added 2026-08-08. Each one makes an existing pattern reach a tag that
		// unsorted.md asked for, with no new pattern row:
		//   {item} {symbol}          chest spike, shoulder spikes
		//   {color} {symbol}         red spike, blue streak, blonde streak
		//   {color} {item} {symbol}  red forehead mark, black ear piercing,
		//                            pink face markings, black hair ornaments
		"spike",
		"spikes",
		"mark",
		"markings",
		"piercing",
		"streak",
		"streaks",
		"ornaments",
    ],
    "size": [
        "tiny",
        "small",
        "big",
        "large",
        "huge",
        "gigantic",
        "hyper",
        "very short",
        "short",
        "medium",
        "long",
        "very long",
        "thin",
        "thick",
        "broad",
        "wide",
        "fat",
    ],
    "state": [
		"flaccid",
		"floppy",
		"sagging",
		"saggy",
		"puffy",
		"perky",
		"plump",
		"pointy",
		"erect",
		"veiny",
		"throbbing",
		"spiked",
		"nubbed",
		"studded",
		"infested",
		"squirming",
		"striped",
		"gaping",
		"prolapsed",
		"multicolored",
		"featureless",
		"obscured",
		"covered",
		"bare",
		"exposed",
		"exposing",
		"presenting",
		"no",
		"unusual",
		"spread",
		"two-tone",
		"sweaty",
		"steaming",
		"cum on",
		"cum on own",
		"cum in",
		// Added 2026-08-08. `{state} {item}` already exists, so these six cover
		// every "<word> (bodypart)" line in unsorted.md without a new pattern:
		// detached arms, flaming hair, furry legs, fluffy tail, mechanical arm,
		// bionic arm. Body only — the clothes generator never reads `state`.
		"detached",
		"furry",
		"fluffy",
		"mechanical",
		"bionic",
	],
	"species": [
		"avian",
		"bird",
		"bull",
		"bunny",
		"dragon",
		"dog",
		"corgi",
		"wolf",
		"canine",
		"cat",
		"feline",
		"ghost",
		"rabbit",
		"squirrel",
		"fox",
		"hyena",
		"deer",
		"reindeer",
		"cow",
		"bull",
		"pig",
		"goat",
		"sheep",
		"ram",
		"elephant",
		"horse",
		"equine",
		"lion",
		"tiger",
		"monkey",
		"mouse",
		"rat",
		"bat",
		"bear",
		"snake",
		
		"fish",
		"dolphin",
		"shark",
		
		"insect",
		"moth",
		"bee",
		
		"humanoid",
		"fairy",
		"angel",
		"demon",
		"robot",
		"doll",
		"slime",
		"alien",
		// Added 2026-08-08. `bull` was already here — `bull horns` failed for a
		// different reason: species reaches the sets ONLY through an inline
		// `(species)` placeholder written into an item array, never through a
		// generator pattern. Adding a word here does nothing on its own; the
		// item needs `(species) horns` alongside it.
		"ghost",
		"dragon",
	],
}