//===================================================================================================
//HONEYCOMB ART PIPELINE -- alternate-outfit designs (brainstorm data, NOT charactersDB)
//===================================================================================================
//Sets A-F for 22 alternate outfits (session 42 round 04 rewrote all 114 non-Anastasia designs). A/B/C are the outfit itself; D/E/F are their LEWD COUNTERPARTS:
//  A = core look, recoloured/re-dressed, HAIRCUT changed      D = lewd A: A's palette/haircut/garments, exposed
//  B = recolour + weapon swap                                  E = lewd B: B's palette/weapon, teased (slit/gap)
//  C = original concept, default ignored                       F = lewd C: C's concept, hypersexualised
//So D must share A's haircut and gear, E must share B's palette and weapon, F must share C's concept. Outfits
//inside one character are built on DIFFERENT silhouettes (trouser-suit vs poncho vs gown, tunic vs gown, etc.),
//and the 57 lewd designs carry a unique medium/tease/tool across the whole lineup. `!tag` swaps an entry trait.
//Read by outfits-generate.js and build-outfits-doc.js.
//
//Constraints honoured (Noodle, 2026-09-15): no cups/coins; loose props positioned; no `holding X` where the
//pose is `palms up` (Clemence); no `veil` where the entry has `hair over eyes` (Nettle) or a blindfold (Cassadora),
//Clemence keeps her signature eye veil; no `wheat` (background) or `locust` (unrecognised); no modern
//technology; and the unviable/overlapping lewd words (pillory, egg, doll, petrification, gambling, taxidermy,
//marionette, and the whole shackle/harness/leash/chastity/gag/shibari/crop/corset cluster) are gone.

module.exports = [

// ===== BRIENNE / knight -- silhouettes: spiked battle plate / enclosing wall plate / cloth alms robes =====
{"character":"knight","name":"Brienne","index":"siegeplate","variant":"A","theme":"Ramhead — armour built to hit with; hair changed to a side shave","tags":["!holding sword","!planted sword","maroon armor","spiked pauldron","single pauldron","spiked gauntlet","single gauntlet","black bodysuit","strapless bodysuit","single pantsleg","bandolier","greatsword on back","armored boots","knight visor","visor up","!ponytail","side shave"],"torn":["torn bodysuit","torn bandolier"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"siegeplate","variant":"B","theme":"recoloured black and gold; the greatsword gives way to a warhammer","tags":["!holding sword","!planted sword","black armor","gold-trim armor","spiked pauldron","single pauldron","gold gauntlet","single gauntlet","white bodysuit","strapless bodysuit","single pantsleg","bandolier","warhammer","gold boots","knight visor","visor up"],"torn":["torn bodysuit","torn bandolier"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"siegeplate","variant":"C","theme":"the siege engine (original) — she wears the ram, helmetless and scarred","tags":["!holding sword","!planted sword","steel armor","mechanical arms","huge gauntlet","steel breastplate","tattered cape","greaves","chain belt","scar","bare shoulders"],"torn":["torn cape"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"siegeplate","variant":"D","theme":"lewd A — the crimson plate over nothing but a sheer suit","tags":["!holding sword","!planted sword","maroon armor","black bodysuit","see-through clothes","spiked pauldron","single pauldron","bandolier","greatsword on back","armored boots","!ponytail","side shave"],"torn":["torn bodysuit"],"tagsV":["underboob","nipples"],"tagsC":["penis outline"]},
{"character":"knight","name":"Brienne","index":"siegeplate","variant":"E","theme":"lewd B — the black-and-gold pauldron straps give","tags":["!holding sword","!planted sword","black armor","gold-trim armor","white bodysuit","strap slip","bandolier","warhammer","single pauldron","gold boots"],"torn":["torn bodysuit"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"siegeplate","variant":"F","theme":"lewd C — the siege engine painted for the breach instead of armoured","tags":["!holding sword","!planted sword","steel armor","body paint","mechanical arms","huge gauntlet","tattered cape","pasties","greaves"],"torn":["torn cape"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"knight","name":"Brienne","index":"bastion","variant":"A","theme":"Portcullis — the wall that walks; hair changed to a bob cut","tags":["!holding sword","!planted sword","steel armor","full armor","helmet","visor down","tower shield","armored skirt","gauntlets","greaves","blue tabard","!ponytail","!forelocks","bob cut"],"torn":["torn tabard"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"bastion","variant":"B","theme":"recoloured bronze and green; the tower shield gives way to a pavise and a mace","tags":["!holding sword","!planted sword","bronze armor","full armor","helmet","visor down","large shield","mace","gauntlets","armored skirt","greaves","green tabard"],"torn":["torn tabard"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"bastion","variant":"C","theme":"the gate (original) — brick, iron and moss; she is the door","tags":["!holding sword","!planted sword","stone armor","brick","huge shield","helmet","visor down","chain","mechanical legs","moss","armored skirt"],"torn":["torn armor"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"bastion","variant":"D","theme":"lewd A — the steel wall with its sides gone","tags":["!holding sword","!planted sword","steel armor","sideless outfit","tower shield","gauntlets","armored skirt","greaves","!ponytail","!forelocks","bob cut"],"torn":["torn armor"],"tagsV":["sideboob","nipples"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"bastion","variant":"E","theme":"lewd B — a vent opens in the bronze tassets","tags":["!holding sword","!planted sword","bronze armor","hip vent","large shield","mace","green tabard","armored skirt","greaves"],"torn":["torn tabard"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"bastion","variant":"F","theme":"lewd C — the gate seeping, its stone gone soft","tags":["!holding sword","!planted sword","stone armor","slime","huge shield","mechanical legs","moss","pasties","wet"],"torn":["torn armor"],"tagsV":["nipples","navel"],"tagsC":["covered penis"]},

{"character":"knight","name":"Brienne","index":"almoner","variant":"A","theme":"Tithe — the almsgiving knight; hair changed to a braided bun","tags":["!holding sword","!planted sword","white robe","gold-trim robe","wide sleeves","gold sash","chainmail","leather pouch","holding book","gold circlet","sandals","!ponytail","braided bun"],"torn":["torn robe"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"almoner","variant":"B","theme":"recoloured blue and silver; the book gives way to a key ring and a lantern","tags":["!holding sword","!planted sword","blue robe","silver-trim robe","wide sleeves","silver sash","chainmail","leather pouch","key","holding lantern","silver circlet","sandals"],"torn":["torn robe"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"almoner","variant":"C","theme":"the collector (original) — an iron mask and a ledger chained to the wrist","tags":["!holding sword","!planted sword","black robe","black mask","chain","holding book","leather pouch","hood up","black gloves","barefoot"],"torn":["torn robe"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"almoner","variant":"D","theme":"lewd A — the white alms robe hanging open","tags":["!holding sword","!planted sword","white robe","open robe","gold sash","chainmail","leather pouch","gold circlet","pasties","!ponytail","braided bun"],"torn":["torn robe"],"tagsV":["underboob","navel"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"almoner","variant":"E","theme":"lewd B — a slit up the blue robe beside the lantern","tags":["!holding sword","!planted sword","blue robe","side slit","silver sash","key","holding lantern","thigh strap","sandals"],"torn":["torn robe"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"knight","name":"Brienne","index":"almoner","variant":"F","theme":"lewd C — the collector's tally kept on the debtor's skin","tags":["!holding sword","!planted sword","black robe","body writing","black mask","chain","hood up","pasties","barefoot"],"torn":["torn robe"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

// ===== NETTLE / necro -- silhouettes: tattered reaper tunic / layered mushroom gown / off-shoulder belle gown =====
{"character":"necro","name":"Nettle","index":"rotsinger","variant":"A","theme":"Blightwail — the ruined harvest; hair changed to a side braid","tags":["green tunic","tattered tunic","black leggings","leg wraps","green hood","hood up","bone necklace","holding sickle","detached sleeves","barefoot","!flaming ponytail","side braid"],"torn":["torn tunic"],"tagsV":["navel"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"rotsinger","variant":"B","theme":"recoloured bone-white and ash; the sickle gives way to a scythe and a censer","tags":["white tunic","tattered tunic","grey leggings","leg wraps","white hood","hood up","bone hair ornament","scythe","holding bell","detached sleeves","ash"],"torn":["torn tunic"],"tagsV":["navel"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"rotsinger","variant":"C","theme":"the carrion choir (original) — a bird-skull mask and a mantle of feathers","tags":["bird skull mask","black tattered dress","feather mantle","black wings","bandages","holding bell","barefoot","claws"],"torn":["torn clothes"],"tagsV":["navel"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"rotsinger","variant":"D","theme":"lewd A — the green tunic worn down to gauze","tags":["green tunic","see-through clothes","leg wraps","bone necklace","holding sickle","barefoot","!flaming ponytail","side braid"],"torn":["torn tunic"],"tagsV":["nipples","navel"],"tagsC":["penis outline"]},
{"character":"necro","name":"Nettle","index":"rotsinger","variant":"E","theme":"lewd B — a slit up the bone-white tunic","tags":["white tunic","side slit","leg wraps","scythe","bone hair ornament","thigh strap","ash"],"torn":["torn tunic"],"tagsV":["navel","sideboob"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"rotsinger","variant":"F","theme":"lewd C — the carrion choir coming unwrapped","tags":["bird skull mask","bandages","feather mantle","black wings","pasties","claws","barefoot"],"torn":["torn bandages"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"necro","name":"Nettle","index":"sporemother","variant":"A","theme":"Contagion — mother of spores; hair changed to double buns","tags":["orange dress","layered dress","long dress","mushroom hat","orange mushroom on shoulder","detached sleeves","pelvic curtain","platform shoes","holding staff","spores","!flaming ponytail","!sidelocks","double bun"],"torn":["torn dress"],"tagsV":["navel"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"sporemother","variant":"B","theme":"recoloured teal and cream; the staff gives way to a parasol and a lantern","tags":["teal dress","layered dress","long dress","beige mushroom hat","beige mushroom on shoulder","detached sleeves","pelvic curtain","platform shoes","holding parasol","vines","spores"],"torn":["torn dress"],"tagsV":["navel"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"sporemother","variant":"C","theme":"the fruiting body (original) — the mushroom has grown through her","tags":["huge mushroom on back","mushroom hat","moss","vines","moss","tattered dress","spores","barefoot"],"torn":["torn dress"],"tagsV":["navel"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"sporemother","variant":"D","theme":"lewd A — the double-bun spore gown reduced to its curtain","tags":["orange dress","pasties","mushroom hat","orange mushroom on shoulder","pelvic curtain","spores","!flaming ponytail","!sidelocks","double bun"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"sporemother","variant":"E","theme":"lewd B — a cutout opens in the teal gown under the parasol","tags":["teal dress","cleavage cutout","beige mushroom hat","holding parasol","pelvic curtain","vines","platform shoes"],"torn":["torn dress"],"tagsV":["cleavage","underboob"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"sporemother","variant":"F","theme":"lewd C — the fruiting body wet with its own spores","tags":["huge mushroom on back","vines","moss","spores","wet","pasties","barefoot"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"necro","name":"Nettle","index":"nightshade","variant":"A","theme":"Venom — the poisonous bloom; hair changed to a hime cut","tags":["purple dress","off-shoulder dress","long dress","purple flower hair ornament","purple flower chest ornament","black gloves","long gloves","choker","detached sleeves","holding vial","!flaming ponytail","hime cut"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"nightshade","variant":"B","theme":"recoloured black and red; the vial gives way to a folding fan and a hairpin","tags":["black dress","off-shoulder dress","long dress","red flower hair ornament","red flower chest ornament","red gloves","long gloves","choker","detached sleeves","holding fan","hairpin"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"nightshade","variant":"C","theme":"the belladonna (original) — the gown IS the flower","tags":["flower dress","petals","flower crown","vines","bare shoulders","long dress","purple flower chest ornament","barefoot"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"nightshade","variant":"D","theme":"lewd A — the hime-cut bloom in a gown gone transparent","tags":["purple dress","see-through clothes","purple flower chest ornament","black gloves","long gloves","holding vial","choker","!flaming ponytail","hime cut"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["penis outline"]},
{"character":"necro","name":"Nettle","index":"nightshade","variant":"E","theme":"lewd B — the black hem lifts behind the fan","tags":["black dress","panty peek","red flower chest ornament","red gloves","long gloves","holding fan","garter straps"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"necro","name":"Nettle","index":"nightshade","variant":"F","theme":"lewd C — the belladonna held open by her own vines","tags":["flower dress","tentacles","vines","petals","flower crown","pasties","barefoot"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

// ===== SEVERINE / vamp -- silhouettes: hunting coat and breeches / regal gown and fur / white saint's coat =====
{"character":"vamp","name":"Severine","index":"huntress","variant":"A","theme":"Feast — hunter of the wounded; hair changed to a low ponytail","tags":["green coat","long coat","fur collar","white ascot","black gloves","fingerless gloves","brown pants","brown boots","tricorne","green hat feather","knife on hip","!long hair","!wavy hair","low ponytail"],"torn":["torn coat","torn breeches"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"huntress","variant":"B","theme":"recoloured grey and rust; the knife gives way to a crossbow and a hunting horn","tags":["grey coat","long coat","fur collar","orange ascot","grey gloves","fingerless gloves","black pants","black boots","tricorne","orange hat feather","axe","holding horn"],"torn":["torn coat","torn breeches"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"huntress","variant":"C","theme":"the pack (original) — pelts and a wolf's skull, the coat abandoned","tags":["skull mask","fur cloak","fur cloak","bandages","bone necklace","claws","barefoot","bare shoulders"],"torn":["torn bandages"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"huntress","variant":"D","theme":"lewd A — the green hunting coat over nothing at all","tags":["green coat","open coat","no shirt","fur collar","brown pants","knife on hip","brown boots","!long hair","!wavy hair","low ponytail"],"torn":["torn coat"],"tagsV":["cleavage","sideboob"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"huntress","variant":"E","theme":"lewd B — the grey coat comes unbuttoned over the crossbow","tags":["grey coat","unbuttoned","orange ascot","black pants","axe","strap slip","black boots"],"torn":["torn coat"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"huntress","variant":"F","theme":"lewd C — the pack after the kill, red to the elbow","tags":["fur cloak","fur cloak","skull mask","blood","wet","pasties","claws","barefoot"],"torn":["torn bandages"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"vamp","name":"Severine","index":"crimsonCovenant","variant":"A","theme":"Bloodletting — the regal red; hair changed to twin drills","tags":["red dress","long dress","off-shoulder dress","red fur cape","red gem chest ornament","crown","black gloves","long gloves","choker","red boots","!long hair","!wavy hair","twin drills"],"torn":["torn dress","torn cape"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"crimsonCovenant","variant":"B","theme":"recoloured white and gold; the crown gives way to a tiara and a rapier","tags":["white dress","long dress","off-shoulder dress","white fur cape","gold gem chest ornament","tiara","white gloves","long gloves","choker","gold boots","rapier"],"torn":["torn dress","torn cape"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"crimsonCovenant","variant":"C","theme":"the covenant (original) — a gown of mail and an iron crown, barefoot on stone","tags":["chainmail","chainmail dress","iron crown","chain","bare shoulders","blood","red gem chest ornament","barefoot"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"crimsonCovenant","variant":"D","theme":"lewd A — the twin-drilled queen in red glass","tags":["red dress","see-through clothes","red fur cape","crown","black gloves","long gloves","choker","!long hair","!wavy hair","twin drills"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["penis outline"]},
{"character":"vamp","name":"Severine","index":"crimsonCovenant","variant":"E","theme":"lewd B — the white gown cut deep beside the rapier","tags":["white dress","plunging neckline","white fur cape","tiara","rapier","garter straps","gold boots"],"torn":["torn dress"],"tagsV":["cleavage","sideboob"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"crimsonCovenant","variant":"F","theme":"lewd C — the covenant's mail ringed through her","tags":["chainmail dress","nipple piercing","piercing","iron crown","chain","blood","barefoot"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"vamp","name":"Severine","index":"bloodSaint","variant":"A","theme":"Transfusion — the sainted vampire; hair changed to a hair bun","tags":["white coat","long coat","white ascot","white gloves","long gloves","white pants","white boots","halo","gold cuffs","cross necklace","!long hair","!wavy hair","hair bun"],"torn":["torn coat","torn pants"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"bloodSaint","variant":"B","theme":"recoloured black and rose; the halo gives way to a stole and a censer","tags":["black coat","long coat","pink ascot","black gloves","long gloves","pink pants","black boots","stole","holding bell","gold cuffs"],"torn":["torn coat","torn pants"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"bloodSaint","variant":"C","theme":"the reliquary (original) — bandaged, haloed, hung with glass","tags":["bandages","white robe","halo","glass vial","chain","blood","cross necklace","barefoot"],"torn":["torn bandages"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"bloodSaint","variant":"D","theme":"lewd A — the saint's white coat over bare skin","tags":["white coat","open coat","no shirt","white pants","halo","white gloves","long gloves","!long hair","!wavy hair","hair bun"],"torn":["torn coat"],"tagsV":["cleavage","underboob"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"bloodSaint","variant":"E","theme":"lewd B — the rose stole slips off a shoulder","tags":["black coat","strap slip","pink ascot","pink pants","holding bell","stole","black boots"],"torn":["torn coat"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"vamp","name":"Severine","index":"bloodSaint","variant":"F","theme":"lewd C — the reliquary labelled in ink instead of glass","tags":["bandages","body writing","halo","chain","blood","pasties","barefoot"],"torn":["torn bandages"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

// ===== CLEMENCE / priest -- silhouettes: apron field-kit / flowing rapture gown / heavy layered habit / sackcloth
// She keeps her signature eye veil, and NOTHING is `holding` (her pose is palms up) -- props sit on the floor.
{"character":"priest","name":"Clemence","index":"devotee","variant":"A","theme":"Ward — the field healer; hair changed to twin braids","tags":["beige blouse","long-sleeved blouse","white apron","white veil","eye veil","bandages","brown belt","long skirt","boots","cross print","!long hair","!wavy hair","twin braids"],"torn":["torn apron","torn blouse"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"devotee","variant":"B","theme":"recoloured sage and oat; the apron gives way to a tabard and a satchel","tags":["tan blouse","long-sleeved blouse","green tabard","white veil","eye veil","bandages","leather belt","green skirt","boots","leather pouch"],"torn":["torn tabard","torn blouse"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"devotee","variant":"C","theme":"the ward (original) — wrapped hands and a lantern set on the floor","tags":["white habit","bandaged hands","white veil","eye veil","lantern on floor","prayer beads","long dress","barefoot"],"torn":["torn habit"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"devotee","variant":"D","theme":"lewd A — the twin-braided healer in the apron alone","tags":["white apron","naked apron","white veil","eye veil","bandages","boots","!long hair","!wavy hair","twin braids"],"torn":["torn apron"],"tagsV":["sideboob","nipples"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"devotee","variant":"E","theme":"lewd B — the oat blouse loose under the sage tabard","tags":["tan blouse","unbuttoned shirt","green tabard","white veil","eye veil","green skirt","side slit","boots"],"torn":["torn blouse"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"devotee","variant":"F","theme":"lewd C — the ward's prayers written where the wounds were","tags":["white habit","body writing","white veil","eye veil","bandages","prayer beads","pasties"],"torn":["torn habit"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"priest","name":"Clemence","index":"ecstatic","variant":"A","theme":"Rapture — the one who runs at it; hair changed to a side braid","tags":["pink dress","long dress","flowing dress","white veil","eye veil","gold capelet","gold cuffs","bare shoulders","halo","barefoot","!long hair","!wavy hair","side braid"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"ecstatic","variant":"B","theme":"recoloured ivory and violet; the halo gives way to wings and a circlet","tags":["beige dress","long dress","flowing dress","white veil","eye veil","violet capelet","gold cuffs","feathered wings","gold circlet","barefoot"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"ecstatic","variant":"C","theme":"the ascension (original) — light coming through a habit that is failing","tags":["white habit","tattered dress","glowing","glowing","white veil","eye veil","feathered wings","halo","barefoot"],"torn":["torn habit"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"ecstatic","variant":"D","theme":"lewd A — the rose gown gone to light","tags":["pink dress","see-through clothes","white veil","eye veil","gold capelet","pasties","barefoot","!long hair","!wavy hair","side braid"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["penis outline"]},
{"character":"priest","name":"Clemence","index":"ecstatic","variant":"E","theme":"lewd B — a slit opens up the ivory gown as she rises","tags":["beige dress","side slit","white veil","eye veil","violet capelet","feathered wings","thigh strap","barefoot"],"torn":["torn dress"],"tagsV":["cleavage","sideboob"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"ecstatic","variant":"F","theme":"lewd C — the ascension burning off the last of the habit","tags":["white habit","glowing","glowing","wet","white veil","eye veil","feathered wings","pasties"],"torn":["torn habit"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"priest","name":"Clemence","index":"abbess","variant":"A","theme":"Rule — the abbess who breaks them; hair changed to a hair bun","tags":["black habit","layered habit","white veil","eye veil","black hood","gold cuffs","prayer beads","long dress","black gloves","!long hair","!wavy hair","hair bun"],"torn":["torn habit"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"abbess","variant":"B","theme":"recoloured white and crimson; the beads give way to a crosier and a stole","tags":["white habit","layered habit","white veil","eye veil","maroon hood","gold cuffs","maroon stole","staff","long dress","white gloves"],"torn":["torn habit"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"abbess","variant":"C","theme":"the cathedral (original) — she wears the church, glass and gold","tags":["stained glass","gold armor","white habit","white veil","eye veil","halo","gold crown","long dress","candle on floor"],"torn":["torn habit"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"abbess","variant":"D","theme":"lewd A — the black habit with its sides gone","tags":["black habit","sideless outfit","white veil","eye veil","black hood","black gloves","pasties","!long hair","!wavy hair","hair bun"],"torn":["torn habit"],"tagsV":["sideboob","nipples"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"abbess","variant":"E","theme":"lewd B — a vent in the crimson habit beside the crosier","tags":["white habit","hip vent","white veil","eye veil","maroon stole","staff","garter straps","white gloves"],"torn":["torn habit"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"abbess","variant":"F","theme":"lewd C — the cathedral lacquered, its glass worn on skin","tags":["stained glass","latex bodysuit","gold armor","white veil","eye veil","halo","gold crown","pasties"],"torn":["torn habit"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"priest","name":"Clemence","index":"penitent","variant":"A","theme":"Penance — sackcloth and ash; hair changed to a low bun","tags":["brown sackcloth","tattered dress","rope belt","white veil","eye veil","ash","bare shoulders","bandages","barefoot","!long hair","!wavy hair","low bun"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"penitent","variant":"B","theme":"recoloured grey and bone; the rope gives way to chains and a floor bell","tags":["grey sackcloth","tattered dress","chain belt","white veil","eye veil","ash","bone hair ornament","bell on floor","barefoot"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"penitent","variant":"C","theme":"the mourner (original) — black wrappings and a mask of tears","tags":["black tattered dress","bandages","black mask","ash","chain","tattered cloak","white veil","eye veil","barefoot"],"torn":["torn bandages"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"penitent","variant":"D","theme":"lewd A — the sackcloth worn thin enough to read through","tags":["brown sackcloth","see-through clothes","rope belt","white veil","eye veil","ash","barefoot","!long hair","!wavy hair","low bun"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["penis outline"]},
{"character":"priest","name":"Clemence","index":"penitent","variant":"E","theme":"lewd B — the grey sackcloth rent at the side over the chains","tags":["grey sackcloth","side slit","chain belt","white veil","eye veil","bone hair ornament","ash","barefoot"],"torn":["torn dress"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"priest","name":"Clemence","index":"penitent","variant":"F","theme":"lewd C — the mourner unwrapping in the rain","tags":["black tattered dress","bandages","black mask","wet","ash","chain","pasties","barefoot"],"torn":["torn bandages"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

// ===== CASSADORA / seer -- silhouettes: star gown / pinstripe trouser suit / patchwork bog poncho =====
{"character":"seer","name":"Cassadora","index":"soothsayer","variant":"A","theme":"Star-Read — the firmament reader; hair changed to a hair bun","tags":["black gown","long dress","star print","blue inner cape","crescent-star clasp","silver star hair ornament","black gloves","long gloves","thighboots","holding crystal ball","!side ponytail","hair bun"],"torn":["torn dress","torn cape"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"soothsayer","variant":"B","theme":"recoloured indigo and silver; the crystal ball gives way to a tarot card and a floating orb","tags":["violet gown","long dress","star print","silver inner cape","moon hair ornament","silver gloves","long gloves","silver thighboots","holding tarot card","floating orb"],"torn":["torn dress","torn cape"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"soothsayer","variant":"C","theme":"the constellation (original) — the sky itself worn as a dress","tags":["star print","star print","glowing","glowing","long dress","bare shoulders","floating orb","barefoot"],"torn":["torn dress"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"soothsayer","variant":"D","theme":"lewd A — the star gown gone to glass around the orb","tags":["black gown","see-through clothes","star print","blue inner cape","black gloves","long gloves","pasties","holding crystal ball","!side ponytail","hair bun"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["penis outline"]},
{"character":"seer","name":"Cassadora","index":"soothsayer","variant":"E","theme":"lewd B — the indigo gown open all down the back","tags":["violet gown","backless dress","star print","silver inner cape","holding tarot card","thigh strap","silver thighboots"],"torn":["torn dress"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"soothsayer","variant":"F","theme":"lewd C — the constellation painted straight onto the reader","tags":["star print","body paint","glowing","glowing","floating orb","pasties","barefoot"],"torn":["torn dress"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"seer","name":"Cassadora","index":"grifter","variant":"A","theme":"Confidence — the card sharp; hair changed to twin drills","tags":["pinstripe vest","white dress shirt","rolled-up sleeves","green necktie","black pants","suspenders","black gloves","fingerless gloves","dress shoes","holding playing card","!side ponytail","twin drills"],"torn":["torn vest","torn shirt"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"grifter","variant":"B","theme":"recoloured burgundy and cream; the cards give way to a cane and a top hat","tags":["maroon vest","beige dress shirt","rolled-up sleeves","black bowtie","beige pants","suspenders","black gloves","fingerless gloves","dress shoes","holding cane","top hat"],"torn":["torn vest","torn shirt"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"grifter","variant":"C","theme":"the ringmaster (original) — tails, a monocle and a cane","tags":["red coat","top hat","black pants","white dress shirt","black bowtie","holding cane","monocle","white gloves","boots"],"torn":["torn tailcoat"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"grifter","variant":"D","theme":"lewd A — the twin-drilled sharp bets the shirt","tags":["pinstripe vest","no shirt","green necktie","black pants","suspenders","black gloves","fingerless gloves","holding playing card","!side ponytail","twin drills"],"torn":["torn vest"],"tagsV":["sideboob","navel"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"grifter","variant":"E","theme":"lewd B — the cream shirt comes undone around the cane","tags":["maroon vest","unbuttoned shirt","beige dress shirt","black bowtie","beige pants","holding cane","top hat","garter straps"],"torn":["torn shirt"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"grifter","variant":"F","theme":"lewd C — the ringmaster lacquered for the last act","tags":["red coat","latex bodysuit","top hat","black bowtie","holding cane","pasties","thighboots"],"torn":["torn tailcoat"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"seer","name":"Cassadora","index":"hedgeWitch","variant":"A","theme":"Bog-Sight — the swamp oracle; hair changed to low twintails","tags":["patchwork poncho","tattered cloak","hood up","green shawl","bone necklace","leather belt","brown skirt","raven on shoulder","barefoot","!side ponytail","low twintails"],"torn":["torn cloak","torn skirt"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"hedgeWitch","variant":"B","theme":"recoloured rust and moss; the raven gives way to a frog and a lantern","tags":["orange poncho","tattered cloak","hood up","green shawl","bone necklace","rope belt","orange skirt","frog on shoulder","holding lantern","barefoot"],"torn":["torn cloak","torn skirt"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"hedgeWitch","variant":"C","theme":"the mire (original) — she has grown into the bog, antlers and all","tags":["moss","vines","moss","tattered dress","antlers","bone necklace","barefoot","bare shoulders"],"torn":["torn clothes"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"hedgeWitch","variant":"D","theme":"lewd A — the patchwork poncho hanging open","tags":["patchwork poncho","open clothes","green shawl","bone necklace","brown skirt","pasties","barefoot","!side ponytail","low twintails"],"torn":["torn cloak"],"tagsV":["sideboob","navel"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"hedgeWitch","variant":"E","theme":"lewd B — a slit up the rust skirt beside the lantern","tags":["orange poncho","side slit","green shawl","orange skirt","frog on shoulder","holding lantern","thigh strap","barefoot"],"torn":["torn skirt"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"seer","name":"Cassadora","index":"hedgeWitch","variant":"F","theme":"lewd C — the mire risen to the waist","tags":["moss","vines","slime","tattered dress","wet","pasties","barefoot"],"torn":["torn clothes"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

// ===== CINDER / lancer -- silhouettes: plumed cavalier / military uniform / ember dancer's crop top =====
{"character":"lancer","name":"Cinder","index":"vanguardPlume","variant":"A","theme":"Comet — the charge itself; hair changed to a high ponytail","tags":["purple cloak","long cloak","wide brim hat","purple hat feather","bronze breastplate","white blouse","purple shorts","white tights","thighboots","flaming spear","!medium hair","high ponytail"],"torn":["torn cloak","torn tights"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"vanguardPlume","variant":"B","theme":"recoloured crimson and brass; the spear gives way to a lance and a banner","tags":["!holding spear","maroon cloak","long cloak","wide brim hat","maroon hat feather","bronze breastplate","beige blouse","maroon shorts","beige tights","thighboots","lance","banner"],"torn":["torn cloak","torn tights"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"vanguardPlume","variant":"C","theme":"the comet (original) — hat gone, hair burning behind her","tags":["flaming hair","fire","bronze armor","tattered cloak","flaming spear","thighboots","motion lines","bare shoulders"],"torn":["torn cloak"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"vanguardPlume","variant":"D","theme":"lewd A — the purple charge in a blouse gone sheer","tags":["purple cloak","see-through clothes","bronze breastplate","white blouse","purple shorts","flaming spear","pasties","!medium hair","high ponytail"],"torn":["torn cloak"],"tagsV":["nipples","navel"],"tagsC":["penis outline"]},
{"character":"lancer","name":"Cinder","index":"vanguardPlume","variant":"E","theme":"lewd B — a gust takes the crimson cloak off the lance","tags":["!holding spear","maroon cloak","wind lift","maroon shorts","beige blouse","lance","banner","thigh strap","beige tights"],"torn":["torn cloak"],"tagsV":["cleavage","sideboob"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"vanguardPlume","variant":"F","theme":"lewd C — the comet with the armour painted on","tags":["!holding spear","flaming hair","fire","body paint","bronze armor","tattered cloak","pasties","thighboots"],"torn":["torn cloak"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"lancer","name":"Cinder","index":"marshal","variant":"A","theme":"Standard — the officer; hair changed to a braided bun","tags":["!holding spear","blue military uniform","epaulettes","gold-trim uniform","white gloves","blue pants","black boots","peaked cap","rapier","gold buttons","!medium hair","braided bun"],"torn":["torn uniform","torn trousers"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"marshal","variant":"B","theme":"recoloured green and silver; the sabre gives way to a baton and a bugle","tags":["!holding spear","green military uniform","epaulettes","silver-trim uniform","white gloves","green pants","brown boots","green peaked cap","rapier","banner","silver buttons"],"torn":["torn uniform","torn trousers"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"marshal","variant":"C","theme":"the colours (original) — wrapped in the banner she carries","tags":["!holding spear","banner","torn flag","bronze breastplate","bandages","gold-trim cape","bare shoulders","boots","epaulettes"],"torn":["torn bandages"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"marshal","variant":"D","theme":"lewd A — the blue uniform open to the belt","tags":["!holding spear","blue military uniform","open clothes","no shirt","gold-trim uniform","white gloves","blue pants","rapier","!medium hair","braided bun"],"torn":["torn uniform"],"tagsV":["cleavage","underboob"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"marshal","variant":"E","theme":"lewd B — the green order comes undone around the baton","tags":["!holding spear","green military uniform","unbuttoned shirt","green pants","rapier","banner","garter straps","brown boots"],"torn":["torn uniform"],"tagsV":["cleavage"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"marshal","variant":"F","theme":"lewd C — the colours lacquered to the standard-bearer","tags":["!holding spear","banner","torn flag","latex bodysuit","bandages","bronze breastplate","pasties","boots"],"torn":["torn bandages"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

{"character":"lancer","name":"Cinder","index":"ashfall","variant":"A","theme":"Ember — the ash-road dancer; hair changed to a side braid","tags":["!holding spear","black crop top","midriff","navel","black harem pants","gold anklet","gold bangles","sheer shawl","ash","embers","barefoot","!medium hair","side braid"],"torn":["torn crop top","torn harem pants"],"tagsV":["underboob"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"ashfall","variant":"B","theme":"recoloured white and ember-orange; the shawl gives way to a long scarf and chimes","tags":["!holding spear","white crop top","midriff","navel","orange harem pants","silver anklet","silver bangles","long scarf","ash","embers","barefoot"],"torn":["torn crop top","torn harem pants"],"tagsV":["underboob"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"ashfall","variant":"C","theme":"the kiln (original) — cracked skin with a coal-red glow behind it","tags":["!holding spear","scar","glowing","embers","fire","bandages","gold bangles","bare shoulders","barefoot"],"torn":["torn bandages"],"tagsV":["underboob"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"ashfall","variant":"D","theme":"lewd A — the side-braided dancer down to the bangles","tags":["!holding spear","black crop top","micro bikini","black harem pants","gold anklet","gold bangles","embers","barefoot","!medium hair","side braid"],"torn":["torn crop top"],"tagsV":["underboob","navel"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"ashfall","variant":"E","theme":"lewd B — a vent opens in the orange harem pants","tags":["!holding spear","white crop top","hip vent","orange harem pants","long scarf","silver bangles","embers","barefoot"],"torn":["torn harem pants"],"tagsV":["sideboob"],"tagsC":["bulge"]},
{"character":"lancer","name":"Cinder","index":"ashfall","variant":"F","theme":"lewd C — the kiln painted in its own ash","tags":["!holding spear","scar","glowing","body paint","embers","fire","pasties","barefoot"],"torn":["torn bandages"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},

	//ANASTASIA. Three silhouettes that share nothing: carved court gown / headsman's apron and bare
	//arms / asymmetric clockwork half-frame.
	{"character":"chess","name":"Anastasia","index":"radiant","variant":"A","theme":"Alabaster — the white queen carved out of the board; hair changed to a crown braid","tags":["white dress","long dress","high collar","wide sleeves","gold-trim dress","tiara","gold necklace","chain necklace","white gloves","elbow gloves","checkered trim","white thighhighs","white boots","high-heeled boots","holding scepter","!side ponytail","crown braid"],"torn":["torn dress","torn gloves"],"tagsV":["cleavage"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"radiant","variant":"B","theme":"recoloured silver and ice-blue; the scepter gives way to an hourglass and a halo","tags":["silver dress","long dress","high collar","wide sleeves","blue-trim dress","silver tiara","silver necklace","chain necklace","white gloves","elbow gloves","blue thighhighs","silver boots","high-heeled boots","holding hourglass","halo","snowflake hair ornament"],"torn":["torn dress","torn gloves"],"tagsV":["cleavage"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"radiant","variant":"C","theme":"the white knight's plate (original) — the gown abandoned for armour","tags":["white armor","breastplate","gauntlets","pauldrons","white cape","gold circlet","white tabard","gold-trim tabard","armored boots","gold belt","holding crown"],"torn":["torn armor","torn cape"],"tagsV":["cleavage"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"radiant","variant":"D","theme":"lewd A — the crown-braided queen in white silk gone sheer","tags":["white dress","see-through clothes","pasties","gold-trim dress","tiara","white gloves","elbow gloves","holding scepter","checkered trim","!side ponytail","crown braid"],"torn":["torn dress"],"tagsV":["underboob","nipples"],"tagsC":["penis outline"]},
	{"character":"chess","name":"Anastasia","index":"radiant","variant":"E","theme":"lewd B — a slit opens up the ice-blue gown around the hourglass","tags":["silver dress","long dress","side slit","blue-trim dress","silver tiara","holding hourglass","halo","garter straps","thigh strap","blue thighhighs"],"torn":["torn dress"],"tagsV":["cleavage","sideboob"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"radiant","variant":"F","theme":"lewd C — the white plate worn as gilding instead of armour","tags":["white armor","body paint","pasties","gold circlet","white cape","armored boots","gold belt","holding crown"],"torn":["torn armor"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},
	{"character":"chess","name":"Anastasia","index":"cruel","variant":"A","theme":"Blackwork — the headsman who takes her own pawns; hair changed to a low bun","tags":["black apron","leather apron","black hood","hood down","bare arms","black gloves","elbow gloves","checkered sash","red sash","belly overhang","black pants","tight pants","black boots","knee boots","cleaver on hip","!side ponytail","hair bun"],"torn":["torn apron","torn pants"],"tagsV":["sideboob"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"cruel","variant":"B","theme":"recoloured oxblood and bone; the cleaver gives way to a chain and a sickle","tags":["red apron","leather apron","white hood","hood down","bare arms","red gloves","elbow gloves","bone hair ornament","belly overhang","black pants","tight pants","brown boots","knee boots","holding chain","sickle on hip"],"torn":["torn apron","torn pants"],"tagsV":["sideboob"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"cruel","variant":"C","theme":"the masked headsman (original) — hooded, wrapped, barefoot on the board","tags":["black hood","hood up","black mask","bandages","bandaged arms","red sash","belly overhang","black pants","barefoot","chain","black collar"],"torn":["torn bandages","torn pants"],"tagsV":["sideboob"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"cruel","variant":"D","theme":"lewd A — the low-bunned headsman in the apron and nothing else","tags":["black apron","naked apron","bare arms","black gloves","elbow gloves","cleaver on hip","checkered sash","red sash","black boots","!side ponytail","hair bun"],"torn":["torn apron"],"tagsV":["sideboob","nipples"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"cruel","variant":"E","theme":"lewd B — the oxblood apron comes loose over the chain","tags":["red apron","leather apron","wardrobe malfunction","bare arms","red gloves","elbow gloves","holding chain","bone hair ornament","belly overhang","black pants","brown boots"],"torn":["torn apron"],"tagsV":["underboob"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"cruel","variant":"F","theme":"lewd C — the masked headsman oiled and coming unwrapped","tags":["black hood","hood up","black mask","bandages","oil","wet","red sash","barefoot","chain","black collar"],"torn":["torn bandages"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},
	{"character":"chess","name":"Anastasia","index":"composed","variant":"A","theme":"Automaton — the bronze half-frame, worn down one side; hair changed to a bob cut","tags":["clockwork","black bodysuit","bronze breastplate","bronze pauldron","single pauldron","bronze gauntlet","single gauntlet","mechanical arms","high collar","gear","pocket watch","bronze thighhigh","single thighhigh","bronze boots","!side ponytail","bob cut"],"torn":["torn bodysuit"],"tagsV":["cleavage"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"composed","variant":"B","theme":"recoloured porcelain and silver; the pocket watch gives way to a pendulum and an hourglass","tags":["clockwork","white bodysuit","silver breastplate","silver pauldron","single pauldron","silver gauntlet","single gauntlet","mechanical arms","high collar","pendulum","hourglass","clock","white thighhigh","single thighhigh","silver boots"],"torn":["torn bodysuit"],"tagsV":["cleavage"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"composed","variant":"C","theme":"the cabinet (original) — the machine closed over her, only the operator's eyes showing","tags":["automaton","bronze armor","mechanical arms","mechanical legs","gear","clock","helmet","visor down","high collar","chain belt"],"torn":["torn armor"],"tagsV":["cleavage"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"composed","variant":"D","theme":"lewd A — the bob-cut automaton's bodysuit cut open down the worn side","tags":["clockwork","black bodysuit","latex bodysuit","cleavage cutout","bronze pauldron","single pauldron","bronze gauntlet","single gauntlet","pocket watch","bronze thighhigh","single thighhigh","!side ponytail","bob cut"],"torn":["torn bodysuit"],"tagsV":["cleavage","underboob"],"tagsC":["erection under clothes"]},
	{"character":"chess","name":"Anastasia","index":"composed","variant":"E","theme":"lewd B — a hip vent opens in the porcelain plating beside the pendulum","tags":["clockwork","white bodysuit","hip vent","silver pauldron","single pauldron","silver gauntlet","single gauntlet","pendulum","hourglass","white thighhigh","single thighhigh","silver boots"],"torn":["torn bodysuit"],"tagsV":["sideboob"],"tagsC":["bulge"]},
	{"character":"chess","name":"Anastasia","index":"composed","variant":"F","theme":"lewd C — the cabinet opened, its workings written across the operator","tags":["automaton","bronze armor","body writing","mechanical arms","gear","clock","pasties","chain belt"],"torn":["torn armor"],"tagsV":["nipples","navel"],"tagsC":["tenting"]},
];
