//GENERATED by build-music-loops.py for music-audition.html. Do not edit.
window.musicMetrics = {
	"trackMap": {
		"title": {
			"index": "title",
			"file": "honeycomb sound/music/loop/title.mp3",
			"loopSeconds": 72.546,
			"fileSeconds": 78.546,
			"postRollSeconds": 6,
			"beats": 97.998,
			"lufs": -19.0,
			"peakDb": -4.2,
			"gainAppliedDb": -4.3,
			"postRollIdentity": 0.99892,
			"seamClickRatioArray": [
				1.78
			],
			"seamSecondsArray": [
				2.961
			],
			"fileBytes": 1572093
		},
		"combat": {
			"index": "combat",
			"file": "honeycomb sound/music/loop/combat.mp3",
			"loopSeconds": 80.0,
			"fileSeconds": 86.0,
			"postRollSeconds": 6,
			"beats": 160.0,
			"lufs": -19.0,
			"peakDb": -3.6,
			"gainAppliedDb": -3.3,
			"postRollIdentity": 0.99978,
			"seamClickRatioArray": [
				0.59,
				1.35
			],
			"seamSecondsArray": [
				48.0,
				0.0
			],
			"fileBytes": 1721513
		},
		"combatShort": {
			"index": "combatShort",
			"file": "honeycomb sound/music/loop/combatShort.mp3",
			"loopSeconds": 48.0,
			"fileSeconds": 54.0,
			"postRollSeconds": 6,
			"beats": 96.0,
			"lufs": -19.0,
			"peakDb": -3.8,
			"gainAppliedDb": -3.5,
			"postRollIdentity": 0.99981,
			"seamClickRatioArray": [
				0.45
			],
			"seamSecondsArray": [
				0.0
			],
			"fileBytes": 1081513
		},
		"map": {
			"index": "map",
			"file": "honeycomb sound/music/loop/map.mp3",
			"loopSeconds": 117.073,
			"fileSeconds": 123.073,
			"postRollSeconds": 6,
			"beats": 160.0,
			"lufs": -19.0,
			"peakDb": -6.3,
			"gainAppliedDb": -7.5,
			"postRollIdentity": 0.9996,
			"seamClickRatioArray": [
				0.85
			],
			"seamSecondsArray": [
				0.0
			],
			"fileBytes": 2462868
		}
	}
};
